### ISSUE TITLE
Feature Request: "Direct" disk mode

### ISSUE THREAD

**Issue by belucid** [dirkwhoffmann/virtualc64#206]
When using Virtual C64 I'm forever losing data because I forget to "Export Disk". I "write" to the disk but that only writes to memory, not to the disk image that's loaded in the virtual drive, until I export the disk (which then doesn't default to the disk image I have loaded) I have to type it or select it. My guess is this must best support the most common use case (game playing?) or it wouldn't be this way.

I know about the warning feature, and I have that turned on, and it's saved me a couple of times, but that only works if you quit Virtual C64. When I lose data that I've not exported it's usually because I've used the reset button, so the warning never kicks in.

So I have a primary feature request of having an optional toggle to "direct" or "export immediate" or some better wording where on disk write the loaded disk image is exported immediately, eliminating the need for the export step.

If that request is rejected or deferred, my secondary request would be to apply the "dirty" un-exported disk warning to the reset button, not just to quitting Virtual C64.

Cheers!

**Comment by dirkwhoffmann** [comment]
Implementing a "write through" mode would be very difficult, because inside the emulator there no real connection between the imported archive (D64, T64, PRG etc.) and the virtual floppy disk. Moreover, a write through would not be possible if a PRG archive was imported (PRG images can only contain 1 file). 

Since 1.0rc2, a reset does no longer delete the virtual disk. Doesn't this solve the problem? 

However, it may help to add a dialog warning the user that the insertion of a new disk deletes the old one. Right now, if a new disk image is dragged into the main screen, the old image gets deleted without any warning.

**Comment by belucid** [comment]
Understandable on the "write through". I didn't know about the 1.0rc2 change. That's very helpful, yes!

I do think a dialog on a "dirty disk" when you eject or insert a new one would be super! That's a pretty common way I end up losing data too. I think that would cover all the real cases with a warning (short of an app crash).

Cheers!

**Comment by dirkwhoffmann** [comment]
A warning dialog is part of 1.0rc4 (which just went online)

**Comment by belucid** [comment]
Thank you Dirk!
