### ISSUE TITLE
Bios ROMS not working with V1.7 Update

### ISSUE THREAD

**Issue by iannorris1976** [dirkwhoffmann/virtualc64#292]
Updated to the new V1.7 today and the emulator will no longer accept the recommended bios ROMS.

Any idea why this is happening?  I have had to delete the V1.7 version and reinstall 1.6

**Comment by dirkwhoffmann** [comment]
Which macOS version are you using?
Does the ROM dialog come up? 
<img width="476" alt="romdialog" src="https://user-images.githubusercontent.com/12561945/36300299-0d27a64a-1301-11e8-846f-ca3984a8881f.png">

I suspect that the new drag and drop implementation (now in Swift) might not work correctly with older macOS versions.

**Comment by GyForget** [comment]
Same here. I'm on 10.13.3. The dialog shows up, but I can't drag the files on it.

**Comment by dirkwhoffmann** [comment]
Drag and drop seems to be messed up in Swift. 

Drag type "NSFilenamesPboardType" (which I used in the old Objective-C implementation) is not available in Swift 4 and the replacement type "URL" is marked "10.13" only. 

I used the workarounds from 

https://stackoverflow.com/questions/44537356/swift-4-nsfilenamespboardtype-not-available-what-to-use-instead-for-registerfo

which work well on my machine. Unfortunately, they don't seem to work everywhere.  I'm going to remove version 1.7 from the web page until it's clear what is going wrong here.

**Comment by iannorris1976** [comment]
Sorry for the late reply.  I am running 10.13.3.  I have since deleted the v1.7 and gone back to v1.6.

**Comment by dirkwhoffmann** [comment]
Could somebody please give the following version a try? 

http://dirkwhoffmann.de/virtualc64/VirtualC64_experimental.zip

In this version, the build target is set to 10.13 and the .fileURL type is used instead of the old stuff. 
If it stills does not work, there is something else going wrong (maybe some firstResponder issue).

**Comment by GyForget** [comment]
This one works! It didn't ask for the ROM files. I moved them so it would request them and I could drag them alright.

**Comment by iannorris1976** [comment]
Yes, that experimental version worked. It only asked for the 1540 bios file, the others were already inserted. 

I tested it with Way Of The Exploding Fist.  Colours were muted compared to the last version but the game ran just fine.  I will try with others when I have more time.

**Comment by dirkwhoffmann** [comment]
I think I figured out how to use the .fileURL drag type (instead of NSFilenamesPboardType) while keeping backwards compatibility with macOS 10.11. The new version is available on the web page (it's named 1.7.1 as the experimental version  I uploaded yesterday, but the implementation is slightly different.)
