### ISSUE TITLE
Keyboard mapping problem

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#296]
Thank you for the implementation but there is a problem for keys and shift.
I have on the keyborad "+" and "*" on the same key (photo) then I need to use shift.
But in the keys assignment I'm not able in using "shift"+ "another key" to obtain the upper letter or symbol on the key.
![34655263-9b7d50c4-f3fe-11e7-89db-179075a899ba](https://user-images.githubusercontent.com/34916641/36627456-54829926-1943-11e8-86a4-b54228aa75b9.jpeg)

**Comment by dirkwhoffmann** [comment]
This is the reason why I left symbolic mapping as a choice. Actually, I ran into exactly the same problem, because the key you mentioned is on a german keyboard, too (at a different location, though). The problem is as follows: 

1. As a "must have" in positional key mapping, I want the shift key hard-wired to the shift key on the C64 keyboard.

Now assume you want to type '*'. On your keyboard, you will:

1. Press SHIFT
2. Press '+'

In step 1, the emulator will set the SHIFT bit immediately in the C64's keyboard matrix. The emulator can't know at this point in time that you'll hit '+' next. If it knew, it shouldn't have set the shift bit because '*' is not shifted on the C64's keyboard. Thus, the requirement to map '+' to '+' and SHIFT+'+' to '*' is contradictory to the "must have" requirement mentioned above.

**Comment by Alessandro1970** [comment]
Ok, but the solution could be to implement a secondary windows for the emulator with a "c64 keyboard like" that one can use winth the mouse ?
![maxresdefault](https://user-images.githubusercontent.com/34916641/36629456-3e1f1df4-1956-11e8-82dd-0ef816c09d7d.jpeg)

**Comment by dirkwhoffmann** [comment]
Yes, a virtual keyboard would be nice add-on. Maybe, one could overlay the C64 screen with a semi-transparent virtual C64 keyboard, that can be operated by the mouse It might not be so easy to implement, though.

**Comment by Alessandro1970** [comment]
Yes ...a semi-transparent virtual C64 keyboard would be a great and a nice add-on !
...Thank you ;-)

**Comment by Alessandro1970** [comment]
A virtual keyboard on a floating window, pressing the respective keys the layout change untill pressed again, so the users can select all the desired keys.
A floating windows for me is the best solution so the users can move it on the desired place in the desktop, then point and click and the letter or symbol will appare on the emulator.
![untitled 5](https://user-images.githubusercontent.com/34916641/37402601-88175fb8-278c-11e8-82bc-03fe28b70c49.jpg)

**Comment by Alessandro1970** [comment]
I prefear to close this issue for the Keyboard mapping problem and open a new one about a virtual keyboard implementation.
