### ISSUE TITLE
Disk/Directory/load/run Dialog in Toolbar

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#306]
Please add the ability to reuse an existing diskette loaded in the drive after a reboot and to select a file to run.

**Comment by Alessandro1970** [comment]
Hi,
Also I think it is very useful to be able to modify the toolbar with the commands "insert disk" and "eject".
In particular, the "insert disk" command could also be placed in the menu before the "eject" command.
VirtualC64 is a great emulator (the best for me!), perfectly integrated with OSX, and with some extra malice it will surely envy all the others ...
Bye

**Comment by dirkwhoffmann** [comment]
Adding "eject" to the toolbar will be an easy task, but what would "insert disk" do? I.e., which disk would be inserted?

The ability to "reuse an existing disk and select a file to run" is difficult because of the following reason: 
When you drag in, e.g., a D64 file, a file browser is shown. This browser displays the contents of the D64 file and not the contents of a disk. When you hit "Insert as disk", the D64 file is converted to a disk. The file browser does not work on disks, so it cannot be shown again after a reboot. BTW, isn't "Open recent" what you intend to have?

**Comment by Alessandro1970** [comment]
a disk insertion option is useful when a program or game is required to insert an additional disk. To this end it would be a dialog box to choose the second or third disk directly in the window (path) where the first disk was located.

**Comment by dirkwhoffmann** [comment]
I am thinking about changing the way disks are inserted, because the current implementation is somewhat inconsistent. E.g., if I use drag and drop to insert a D64 image, everything works like I expect, but if I use the "File->Open" menu to open a D64 image, a new emulator instance is created. This seems to be inconsistent and a new emulator instance is usually not the thing the user wants. 

I think it would be better to distinguish clearly between emulator snapshopts (VC64 format) and disk images (D64, T64 format, etc.). In V2.0, I plan to use the file menu solely for snapshots (because VirtualC64 is a "document type" application and the "documents" are the snapshot files. Hence, in future versions, it won't be possible to load a D64 or T64 file via the file menu. For loading those files I plan to give the "Drive" menu the following structure (mimicking the structure of the "File" menu for disk images):

Drive:  
"New"    Inserts a blank disk
"Insert ..."    Opens a file dialog and let's the user choose a D64, T64 etc. image
"Insert Recent" Like "Open Recent" from the File menu for disks
------
"Eject"   
"Export As ..:" Opens a file dialog and exports ...
------
Power on / off

Drag and drop behavior will stay as it is.

I think the new "Insert Recent" menu item should more or less fit the needs mentioned by the OP. However, when the new menu is in place, I would vote against having a toolbar item with the same functionality. This would result in two different ways (and different implementations) to accomplish the same thing which is bad UI design.

**Comment by Alessandro1970** [comment]
In fact, I wanted to point out that I can not insert the second disc of the Uninvited game.
If I drag the disk image it is not loaded, when the game requires it.

<img width="754" alt="schermata 2018-06-16 alle 11 02 39" src="https://user-images.githubusercontent.com/34916641/41497412-1e37a7d4-7155-11e8-9a2a-48ab9b32c0b7.png">

**Comment by dirkwhoffmann** [comment]
OK, I figured it out. Dragging and dropping a D64 file would indeed change the disk, but I does not work in Uninvited, because the second disk does not have a valid file size. There are six different D64 formats (with fixed file sizes and the second disk does not fit any of these sizes. The bug in the emulator is simply that it does not tell the user about the load error (so one thinks the disk has been inserted, but it hasn't). I'll set up a different bug report for this.

**Comment by Alessandro1970** [comment]
Ok, as soon as I have time, with the Duplicator I will try to copy the files of the second Univited disk into another image .d64.

**Comment by dirkwhoffmann** [comment]
I guess, the second disk contains an unusual number of tracks (something between 36 and 39). If "Duplicator" shows some information about this, I could add support for these D64 files (in the readme.txt file that came with Uninvited, it states that the disk is recognized by the CCS64 emulator).

**Comment by Alessandro1970** [comment]
Hi Dirk,
I can't do anything with the Duplicator, it seems that my images (d64) are really damaged.
Browsing the web I found this version that works great with the VirtualC64:
[](https://csdb.dk/release/?id=101260)

<img width="763" alt="schermata 2018-06-17 alle 09 51 39" src="https://user-images.githubusercontent.com/34916641/41505982-dbb837e6-7214-11e8-8e76-5e0fa187a44b.png">

**Comment by dirkwhoffmann** [comment]
OK, cool. I did some calculations yesterday to see if the file size fits a 36, 37, 38, or 39 track D64 file. Unfortunately, it doesn't, so it seems best to reject the file by the emulator (the new version will show a "File is corrupted" message when reading this file).

**Comment by dirkwhoffmann** [comment]
The "Insert Recent" menu has been implemented in V2.0 beta 1 which can be downloaded at http://www.dirkwhoffmann.de/virtualc64/
