### ISSUE TITLE
VirtualC64 1.9 reports 60Hz in PAL mode

### ISSUE THREAD

**Issue by elmerucr** [dirkwhoffmann/virtualc64#308]
Thanks for this great software! I just upgraded to version 1.9, please have a look at the attachment.
<img width="219" alt="2018-04-15 60fps" src="https://user-images.githubusercontent.com/38407365/38782765-7051b434-40f8-11e8-85d2-b5769e5f2907.png">

**Comment by dirkwhoffmann** [comment]
Actually, this is a feature :). Older versions of the emulator showed the number of frames computed by VIC which is 50 for PAL. However, this information is redundant because it is directly tied to the CPU frequency. From 1.7. on, the emulator displays the GPU frame rate which is 60 Hz on a TFT display. I thought it makes more sense to have some information about GPU performance next to the information how fast the virtual CPU  is running.
