### ISSUE TITLE
Track/Sector editor

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#309]
Beside having a GCR encoded data viewer/editor, can a view be added to view in hex? Or adding a track and sector editor?

**Comment by dirkwhoffmann** [comment]
My plan is to eventually replace the current text view by a table view that displays the GCR data in smaller chunks. Each row would display a chunk and each chunk is started and ended by a SYNC sequence. Each chunk could then easily be displayed as a GCR bitstream or a decoded hex sequence. I didn't implement this, yet, because the code has to very robust. It needs to cope with killer tracks (SYNC bits, only) and other irregularities that occur on copy-protected disks.

**Comment by dirkwhoffmann** [comment]
Fixed in V2.0 beta 1 which can be downloaded at http://www.dirkwhoffmann.de/virtualc64/
