### ISSUE TITLE
Zak McKracken & The Alien Mindbenders hangs

### ISSUE THREAD

**Issue by puleyo** [dirkwhoffmann/virtualc64#315]
Hi,

I cannot start Zak, I used different versions but it hangs and the screen comes black.
Is this the same problem of Maniac Mansion ?

Game link:
http://csdb.dk/release/?id=151574

**Comment by dirkwhoffmann** [comment]
Found it. The culprit was the IEC bus interface which worked well with the original C64 kernel routines, but failed to work with some custom loaders (such as the eagle soft loader).
<img width="812" alt="zack" src="https://user-images.githubusercontent.com/12561945/39622929-30e65bf6-4f94-11e8-8d63-076105c0105a.png">
