### ISSUE TITLE
Help for Lemmings with mouse

### ISSUE THREAD

**Issue by Ottavius** [dirkwhoffmann/virtualc64#316]
Hello,
congratulations for this wonderful emulator for mac.
I would like to know how I can play Lemmings with the mouse of my mac ? 

When I was young I always played Lemmings with my CBM64 with mouse.
I can not find the option to configure the mouse and have the arrow in the window captured by emulator to play Lemmings.

Can someone tell me how to do it?

Thank you

**Comment by dirkwhoffmann** [comment]
There is no mouse support in VirtualC64 yet, but I'll try to add such a feature in one of the next releases.

BTW, nice to hear that Lemmings is working. I've never run it on a C64 (only on PCs).

**Comment by Alessandro1970** [comment]
Hi,

lemmings on VirtualC64 works very well!
It would be great if we can use the 1531 mouse emulation with pointer capture so one can play without losing control of the mouse due to movements outside the VirtualC64 window.
Thank you
Greetings

<img width="811" alt="image" src="https://user-images.githubusercontent.com/34916641/39660815-e9820130-5046-11e8-9e06-a0b864a8cbf5.png">

**Comment by Ottavius** [comment]
Thank you, dirkwhoffmann

**Comment by dirkwhoffmann** [comment]
VirtualC64 1.11 will support three mice models (C1350, C1351, and Neos):

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_1_11_beta.zip

Any feedback on the beta version is highly appreciated.

**Comment by Alessandro1970** [comment]
Lemmings runs perfectly with the 1351 Mouse active on port 2

**Comment by Ottavius** [comment]
Thanks it works great, everything is ok.

**Comment by dirkwhoffmann** [comment]
Fixed in V1.11
