### ISSUE TITLE
Customize keymap issues 

### ISSUE THREAD

**Issue by rpnielsen** [dirkwhoffmann/virtualc64#323]
Trying to customize the keymap I encountered the following:

Attempting to map the “HOME” key to my Mac keyboard’s TAB key (Key 30) has no effect.
 It does say 30 on the displayed key, but actually pressing the TAB key does nothing.

Attempting to map the “STOP” key to my Mac keyboard’s “ESC” key (Would be 35, I guess) causes VirtualC64 to crash the instant I press the ESC key.

- Speaking about keymapping, by the way, what happened to the "RESTORE" key? I can't find it in the keymapping window.

**Comment by dirkwhoffmann** [comment]
Thanks for reporting!

The TAB key bug should be fixed in 1.10 (did you use 1.9?)
Right now, key customization only works for "normal" C64 keys that are connected via the keyboard matrix to the CIA chips. The restore key is special, because it is directly connected to an IRQ line on a real C64. Customizing this special key hasn't been implemented yet.

The emulator should not let you use the ESC key as a C64 key (because it has so many special meanings in OS X such as closing a dialog, exiting full screen mode etc.). I'll try to fix this in the next release.

**Comment by rpnielsen** [comment]
Oh. Yes updating to 1.10 worked for the TAB key.. As for the ESC key I just thought it was the intuitive choise of key for the C64 STOP key. - But thank you very much.
