### ISSUE TITLE
[Feature Request] Ability to disable auto-saved snapshots functionality

### ISSUE THREAD

**Issue by troydm** [dirkwhoffmann/virtualc64#343]
It would be nice to have an checkbox that would disable automatic periodic snapshot functionality

**Comment by dirkwhoffmann** [comment]
What kind of problem did you experience (runtime issue, memory issue)?

**Comment by troydm** [comment]
@dirkwhoffmann no problem however I assume that during each snapshot whole memory is locked so it has some minor performance overhead alas not noticeable on modern hardware because of how powerful it is compared to C64 but I thought that having this functionality would be a nice thing just in case that you want to be sure that everything runs as fast as possible

**Comment by dirkwhoffmann** [comment]
OK, I think this could be integrated nicely by adding the following option to the "Emulator Settings" dialog:

(Checkbox) Take a snapshot every (TextField) seconds. 

However, the performance benefit will be small, because the emulator uses a statically allocated ring buffer for storing the snapshots (filled with placeholders on startup which are not visible to the user). This was done for speedup reasons. Using a static array has the advantage that the emulator does not have to allocate and free memory dynamically. It can just dump the current emulator state to a certain  memory location (cartridge handling is a little bit more complicated though).

Anyway, I think it's beneficial to the user if he can choose the time interval between two snapshots. So the disable feature can be integrated by simply setting this interval to "infinite" internally.

**Comment by Alessandro1970** [comment]
I do not use automatic snapshot, if it will be the way to disable that system it would be a good thing for me.
I prefer a completely manual snapshot system, to be used only if there is the need...

**Comment by dirkwhoffmann** [comment]
Fixed in V2.2 which is online.
