### ISSUE TITLE
Add the Dark Mode support for macOS 10.14 [Mojave] 

### ISSUE THREAD

**Issue by dada08ms** [dirkwhoffmann/virtualc64#356]
Good morning
Could you add the Dark Mode support for macOS 10.14 [Mojave] ?

**Comment by puleyo** [comment]
I like this new Apple OS dark mode !
Thank you for this emulator, now AppleOs users can have a great and fine C64 emulator.
I have seen the add on and the bugs to remove, I hope tha VirtualC64 **2.4** came out very soon, this 2.4 version with more cartridge support, the really needed second 1541 drive and a VICII selectable (6569/8565 -6566/6567/8562) will be the best ever seen on a Mac...!

**Comment by dirkwhoffmann** [comment]
Compiling VirtualC64 with XCode 10.0, dark mode works out of the box: 

<img width="868" alt="bildschirmfoto 2018-09-25 um 15 14 18" src="https://user-images.githubusercontent.com/12561945/45990770-e6f23480-c0d5-11e8-9ecd-9078e635886a.png">

There are some minor text coloring issues though: 

<img width="309" alt="bildschirmfoto 2018-09-25 um 15 15 15" src="https://user-images.githubusercontent.com/12561945/45990797-fffae580-c0d5-11e8-9a83-f4fcad216145.png">

I don't know what you think, but I'm personally pretty disappointed with the new dark mode up to know (just another marketing hype?). Since I installed the latest OS release a couple of hours ago, I tried several of Apple's native apps and for nearly all apps, standard mode appeared much clearer to me and most UI elements were easier to find. I think I'll switch back to standard mode. 

Another problem with dark mode is it's incompatibility with windows drawers (which are used by the debugger). The drawer surrounding remains gray and is not darkened. Drawers have been deprecated by Apple a long time ago, so this won't be fixed by Apple. Eventually, I will have to replace the drawer by something else which is sad, because I think that this (deprecated) UI element perfectly fits the needs for the debugger.

**Comment by Alessandro1970** [comment]
Personally I did not appreciate this dark mode and not all applications make it good in this version. I will keep the usual normal mode on my MBP.
On the VirtualC64 I think the debugger problem is soluble they change the font color (try them with a light gray or green tone).
... I like VirtualC64 in the standard mode and I do not think many users will keep this dark mode ...

**Comment by dirkwhoffmann** [comment]
The text color issue is a no brainer. It only looks wrong if the color is hard-coded (which I did several times 🙄). When complying to coding standards (i.e., NSColor.textColor is used instead of NSColor.black) it looks correct both in dark mode and standard mode: 

<img width="308" alt="bildschirmfoto 2018-09-25 um 15 49 49" src="https://user-images.githubusercontent.com/12561945/45994052-08f3b300-c0e6-11e8-9c8e-2afd611b916c.png">

Code fix for the color issue is already checked in on the master branch.

**Comment by mortinus** [comment]
I like the dark mode and I also like the VirtualC64! In dark mode, the only thing I do not like the icon of the joystick in the toolbar (the square with a light black background). The background of the joystick square icon would have made it light gray in contrast with the black of the toolbar.

**Comment by Alessandro1970** [comment]
The white and red debugger's fonts are fine. I have no problem in reading them.

**Comment by Alessandro1970** [comment]
In fact, the icons in the black toolbar are lost a little

**Comment by Alessandro1970** [comment]
... we should get used to maybe ... to keep the beautiful normal mode ...
But I think that all in all the VirtualC64 goes well even in dark mode: the debugger is readable and black lovers will appreciate it.

**Comment by mortinus** [comment]
Black lovers ...
the reality is that there is a need for a second set of icons based on lighter colors

**Comment by Alessandro1970** [comment]
You could normalize the icons in a circular Yosemite style (even for the size so as to have an ordered arrangement), so that the outer circular crown color will contrast with the dark tool bar while the icon will make it good in its original background color.
I like the icons arranged with the same centering and the same size and this system seems more 'ordered (if all the icons were inserted in circles like the word), but it's just my idea.
![untitled 1](https://user-images.githubusercontent.com/34916641/45995018-8db6e080-c096-11e8-8a4b-495a389ddab4.jpg)

**Comment by mortinus** [comment]
Alessandro is right the circular icons REWIND and BROWSE are in fact **well seen** as that of WORD even if that of Word (a bit larger) would make better.
Circular icons are good in the normal mode too, just like the apple bottom bar...

**Comment by mortinus** [comment]
For the circular border icons inside have their original background, if you put the **Monitor** icon in a circular icon with the gray background it will be seen well in the dark mode as in the normal one...
There in a program in the applestore that convert icon into circular.
![appstore](https://user-images.githubusercontent.com/41686391/45995356-16824c00-c098-11e8-868d-0486a53d104a.jpg)

**Comment by Alessandro1970** [comment]
I have one of them it is called Image2icon and the full version (I do not the free one) make also circular yosemite icon form a normal PNG or JPG.
I have bought it last year from the appstore.
![image2icon-56a5d52d3df78cf7728a0ff6](https://user-images.githubusercontent.com/34916641/45995509-9f998300-c098-11e8-9c76-08dedac2e0b8.jpg)

If you want I can try to convert all the icons of the VirtualC64.

**Comment by Alessandro1970** [comment]
...but I think that the combo boxes color problem will remain in the toolbar

**Comment by Alessandro1970** [comment]
> Maybe VirtualC64 should get similar looking icons.

Yes, that would be the solution !
<img width="932" alt="45996334-fc745800-c0ef-11e8-82db-fbbb629283b2" src="https://user-images.githubusercontent.com/34916641/45997477-fa82a880-c09f-11e8-9eac-e132632d8e66.png">

**Comment by mortinus** [comment]
Ok, for me too !
<img width="932" alt="45996334-fc745800-c0ef-11e8-82db-fbbb629283b2" src="https://user-images.githubusercontent.com/41686391/45997511-24d46600-c0a0-11e8-9313-53f7e55712fb.png">

**Comment by rossimariolee** [comment]
This one is good
<img width="932" alt="45996334-fc745800-c0ef-11e8-82db-fbbb629283b2" src="https://user-images.githubusercontent.com/41687618/45997551-51887d80-c0a0-11e8-80af-4baa5a119ecb.png">

**Comment by puleyo** [comment]
Shrinking the icons and inserting them into small rectangles is the most pleasant solution for me too.
<img width="932" alt="45997551-51887d80-c0a0-11e8-80af-4baa5a119ecb" src="https://user-images.githubusercontent.com/38581054/45997715-cf4c8900-c0a0-11e8-9d4e-e5aaa468d79e.png">

**Comment by DaitarnIII** [comment]
This is the Dark-Mode I like a lot !
For me ok this solution !
Thanks
<img width="932" alt="45997551-51887d80-c0a0-11e8-80af-4baa5a119ecb" src="https://user-images.githubusercontent.com/41691550/45997780-0e7ada00-c0a1-11e8-8e61-016953feced7.png">

**Comment by Alessandro1970** [comment]
> Shrinking the icons and inserting them into small rectangles

Ok!

**Comment by dada08ms** [comment]
I like this kind of little rectangular icons for VirtualC64 for the Dark-Mode.
Thank you
<img width="932" alt="45996334-fc745800-c0ef-11e8-82db-fbbb629283b2" src="https://user-images.githubusercontent.com/40881549/45998455-35d2a680-c0a3-11e8-980e-a67ed7f87343.png">

**Comment by dirkwhoffmann** [comment]
I've deleted the icons from the emulator preferences window, because they didn't look that nice in dark mode. 

<img width="862" alt="bildschirmfoto 2018-09-27 um 18 35 07" src="https://user-images.githubusercontent.com/12561945/46127519-0c717080-c285-11e8-8d93-292f8fae6294.png">

Shall I delete the icons in the hardware dialog as well? One the one hand, my hard would bleed, because it took me a long time to assemble them. On the other hand, it would be more consistent with Apple's new simplistic design philosophy.

<img width="862" alt="bildschirmfoto 2018-09-27 um 18 31 59" src="https://user-images.githubusercontent.com/12561945/46127602-4b072b00-c285-11e8-969b-d56d685c21c1.png">

Because of the large variety of visual changes, I think it might be best to call the new version 3.0. What do you think?

**Comment by Alessandro1970** [comment]
I'm sorry for the time you've lost for the old icons, but I think removing thems would be the best choice with this new spartan look.

I think it's right to go to version 3.0 ... in fact the VirtualC64 is now another thing (for the better).

In 3.0 is it possible (please) to add the support of the cartridges that have been asked by others members ?

**Comment by dada08ms** [comment]
With all these changes it is better to move to version 3.0.
I'm very much in touch with the stingy points:
1) yes to the simple look
2) the ver. 3.0 should have the support of the new CIA so there are no more hardware additions to do, so it makes more sense to "close a chapter"
3) even wait a few more days and go to 3.0 with all the required cartridges supported (Warpdos/Stardos)

In doing so after 3.0, only bugs will be considered in the future ...I think (The VirtualC64 works well)

**Comment by UgoCaneFifone** [comment]
Yes, close issues 2.6 and 2.7, add the new CIA support and upgrade to version 3.0 (all in one) with a simplistic look (which I like a lot).

**Comment by Alessandro1970** [comment]
Hei !? Is not that with the NEW CIA support **you are asking too much** ? :laughing: 

However, the part underneath in bold should be removed !!! :rofl:  :rofl:  :rofl: 

TO BE REMOVED:
**Although the emulator has not yet reached the impressive compatibility of VICE or Hoxs64**, VirtualC64 has evolved into a full-blown C64 emulator over the years.

**Comment by DaitarnIII** [comment]
Does this mean? :laughing: 

![untitled 4](https://user-images.githubusercontent.com/41691550/46134021-305f9280-c242-11e8-8ff1-5ac6899f84e7.jpg)

**Comment by puleyo** [comment]
...Picasso !  :roll_eyes:

**Comment by mithrendal** [comment]
>Shall I delete the icons in the hardware dialog as well?
for my taste you could leave them as they are. They are beautiful!!!

I try to be bold now ;-) Version 3.0 should have support for EZ-Flash Cartrigde (EasyFlash). Reason: almost all of the newer stuff (for example new enhanced speedball2 with icecream speach synthesis) from https://csdb.dk/  _(thec64 Scene Database)_ are made in that .crt format as it has a capacity of 1MB.

**Comment by Alessandro1970** [comment]
Toooo **bold** :laughing: 
![dn_hmevj_400x400](https://user-images.githubusercontent.com/34916641/46135447-7c600680-c245-11e8-8084-bed833d7d333.png)

**Comment by Alessandro1970** [comment]
... too bold.! **..or maybe not ?**
In my opinion Dirk has **already implemented** the support for the new CIA!

![untitled 1](https://user-images.githubusercontent.com/34916641/46140509-999ad200-c251-11e8-8953-64bb6d0858f7.jpg)

**Comment by mortinus** [comment]
> In my opinion Dirk has already implemented the support for the new CIA!

...in this case, version 3.0 can support the 2 new cartridges .... so!

**Comment by Alessandro1970** [comment]
Hei **Waterloo**, you're going a bit too far ! 
 
:wink:
