### ISSUE TITLE
Tape dialog window

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#359]
If I insert a "TAPE" file, VirtualC64 in the dialog window tells me to insert a disk and not a TAPE.

<img width="776" alt="schermata 2018-07-15 alle 10 30 56" src="https://user-images.githubusercontent.com/34916641/42732066-46c6e0a8-881a-11e8-9aff-df2dcbc14fb7.png">

**Comment by Alessandro1970** [comment]
.t64 filese are seen as disks images ?
Once inserted mancopter.t64 the Virtualc64 does not allow me to eject the tape but the disk, strange thing as if mancopter.t64 was a disk

**Comment by dirkwhoffmann** [comment]
T64 files are just archives storing multiple separate files in form of byte streams. This means that these files do neither represent a real disk (such as D64 files) or a real tape (such as TAP files). Therefore, it makes most sense to convert them to a disk rather than a tape, but I understand that the button text is misleading (maybe the icon which is showing a tape is misleading, too). I'll change the button text to "Insert as disk" to make it clear that a conversion takes place.

**Comment by dirkwhoffmann** [comment]
(Presumably) fixed in 2.3 beta 3 

http://www.dirkwhoffmann.de/virtualC64/VirtualC64_2.3_beta3.zip
