### ISSUE TITLE
Let the user choose the VICII model in the hardware preferences panel

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#360]
The introduction of this game has a strange graphic defect in the image of the word "FACES" and I also see a defect in the background mountains on the edge of the screen, if I change the VICII with the American version there is no improvement even worse.

[Catalypse (1992)(Genias)[cr Faces][t +4 Faces].d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/2195603/Catalypse.1992.Genias.cr.Faces.t.%2B4.Faces.d64.zip)

**Comment by dirkwhoffmann** [comment]
VirtualC64 should behave similar to x64sc (cycle based), so it's a bug. It's most likely due to the timing when certain values show up in certain VIC registers. It would be interesting to know how x64sc behaves when a different VIC model is selected (in contrast to VirtualC64, VICE is able to emulate the hardware difference between different VICII chip models).

**Comment by Alessandro1970** [comment]
I noticed in VICE that:
VICII model: 6572 (PAL-N) = same error of the VirtualC64
VICII model: 6569 (PAL) = ok it works
VICII model: 8656 (PAL) = ok it works

![untitled 5](https://user-images.githubusercontent.com/34916641/42808284-431a1ee4-89b3-11e8-8593-26c76f5dfeae.jpg)

**Comment by Ottavius** [comment]
Alessandro You are right, I tried VICE. The intro works with VICII 8656 (PAL) [Custom and Discrete].
I think that VICII 8656 (PAL) is better the the others.

**Comment by Alessandro1970** [comment]
I do not known if there are differences between 6569 and 8656, I think none.
But the 6572 was a sud-american version and it could be the same of the other, there will be some bug in the Vice for that version too.

**Comment by dirkwhoffmann** [comment]
There are indeed subtle differences in respect to timing behavior, i.e., the number of cycles between writing a certain VICII register and the time the new value takes effect. Such differences also exist between the old CIAs and the new ones used in later models. In one CIA model, an interrupt takes effect one cycle later than in the other. Although the VICII hardware differences are very small, they often cause trouble in demos because these programs push the chip capabilities to the extreme.

Good thing is, we have a good test case now for distinguishing both VICII models. In later versions, I'll try to offer multiple VICII chips in the hardware setup. So far, I ignored the hardware differences completely, so I can not even tell which chip model is emulated right now. I suppose, VirtualC64 currently emulates a mixture of both models.

**Comment by Alessandro1970** [comment]
I have tried these demos on the PC with HOXS64 and I must say that the VICII that is used by HOXS64 is the most 'compatible: **all** the demos work very well.
The VICII of the HOXS64 could be loaned by the VirtualC64 ?

_As soon as possible I try the geos with georam and 2 disk drives_
This link for Royal Demo **works**: https://csdb.dk/release/?id=11619

**Comment by Ottavius** [comment]
Is it this one ?
https://github.com/mamedev/mame/blob/master/src/devices/video/mos6566.cpp

**Comment by Alessandro1970** [comment]
No, I do not know.
I just wanted to say that for the tests I've done, the VICII of the HOXS64 seems **to me** more precise than the one in the VICE .... But this is only my opinion ...

**Comment by Alessandro1970** [comment]
Hi, now VirtualC64 ver 2.3 beta2 works well for me with this intro:

<img width="778" alt="schermata 2018-07-22 alle 10 57 15" src="https://user-images.githubusercontent.com/34916641/43044004-38455d8c-8d9e-11e8-85c1-ddd65db73c60.png">

**Comment by dirkwhoffmann** [comment]
Strange enough. I did some speed optimization in the VIC code, so there was a real possibility that something is broken now. Interesting to see that it's the other way round this time.

**Comment by Alessandro1970** [comment]
**Great review this 2.3 beta 2**:
The Royal Arts demo (look up) works like in the VICE now, the others demo I've tried today (many) all works at the best!!! 
<img width="781" alt="schermata 2018-07-22 alle 11 38 08" src="https://user-images.githubusercontent.com/34916641/43044481-f890440a-8da6-11e8-9243-687dd2161407.png">

**Comment by dirkwhoffmann** [comment]
I let the enhance request open, but set it's priority to "Low"

**Comment by puleyo** [comment]
Also in my opinion this last emulation of the VIC II (**2.4 version**) is very good, no problems. 
Thank you

**Comment by dirkwhoffmann** [comment]
#393 is a follow up
