### ISSUE TITLE
Emulamer's Errata Demo does not work in part n. 3

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#387]
Emulamer's Errata Demo does not work in test n. 3 (press space to advance), you should see an image and instead there is a distortion.
I read that it could be an "Illegal opcode tweak" but I do not know if it's the same problem that occurs in VirtualC64.
[errata.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2280002/errata.prg.zip)

VirtualC64 (part 3):
<img width="777" alt="schermata 2018-08-11 alle 09 20 20" src="https://user-images.githubusercontent.com/34916641/43989364-d4e4709c-9d48-11e8-8700-f037a4d4f646.png">

Vice (part 3):
<img width="717" alt="schermata 2018-08-11 alle 09 22 13" src="https://user-images.githubusercontent.com/34916641/43989368-de1f6022-9d48-11e8-966e-711d7a98505c.png">

**Comment by puleyo** [comment]
I tried this demo, the third step,  but also I cannot see the image. The result is the same: the green screen. The first and the second demo work fine.

**Comment by rossimariolee** [comment]
Also I can not see the last image of this demo and I see a green rectangle made up of strange characters like in the picture above

**Comment by Alessandro1970** [comment]
This bug had already been evidently met by the programmers of the HOSX emulator:

**HOXS 11 March 2012 v1.0.7.4:**

1) The application is marked as "DPI Aware". All Windows GUI elements are DPI aware and will render
smooth clear text when used with Windows 7's "make text bigger" option. Only the windowed mode C64
bitmapped rendering remains non DPI aware as with previous versions.
2) Added a work in progress breakpoint listview with context menu options "Show Address" and "Delete
All Breakpoints"
**3) Illegal opcode tweak for demo 'Errata' by Emulamer.**
4) CRASHFIX: Fixed stack corruption crash when reading G64 files with custom speed zones.
5) CRASHFIX: Fixed application lock up bug while drag scrolling the disassembly window.

**Comment by Alessandro1970** [comment]
How does it work ? I have seen there are different series of illegal opcode:
1] http://unusedino.de/ec64/technical/aay/c64/ibmain.htm
2] http://www.oxyron.de/html/opcodes02.html
3] http://codebase64.org/lib/exe/fetch.php?media=base:nomoresecrets-nmos6510unintendedopcodes-20172412.pdf

**Comment by dirkwhoffmann** [comment]
We are on the wrong path here. The errata demo uses illegal instructions in the first part which is working well in VirtualC64.

In the failing picture drawing demo, no illegal instruction seems to be used. (If a snapshot is created during picture drawing and this snapshot is loaded into an emulator without illegal instructions registered, it does not jam the CPU. Hence, no illegal instruction is executed in this demo part.)
Some other special, yet unsupported VICII feature must be used in this demo part.

**Comment by Alessandro1970** [comment]
As we read in INTRO part 3 this demo has the same problem, it should show a green image ...

[ruined_art.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2289558/ruined_art.prg.zip)

**Comment by Alessandro1970** [comment]
Even the last Emulamer demo called "The Conclusion" has problems: it shows the image of the tree but does not show the characters at the bottom of the page.
[Conclusion.zip](https://github.com/dirkwhoffmann/virtualc64/files/2289807/Conclusion.zip)

VirtualC64:
<img width="775" alt="schermata 2018-08-15 alle 11 26 16" src="https://user-images.githubusercontent.com/34916641/44141878-ba81a916-a07e-11e8-962c-dbd743a29d25.png">

VICE (SC):
<img width="718" alt="schermata 2018-08-15 alle 11 29 06" src="https://user-images.githubusercontent.com/34916641/44141893-c32a0fea-a07e-11e8-80d4-550e50fc9d4d.png">

**Comment by puleyo** [comment]
I've tried all three demos:
**Conclusion.zip - ruined_art.prg.zip - errata.prg.zip**
there must be some trick that prevents VirtualC64 from displaying images properly, because the emulator doesn' stop working.
I assume that for all three demos the problem is the same, I'd like to know exactly the cause of this bug or trick that is ....

**Comment by Alessandro1970** [comment]
I do not know if it can be some help but I found that if you rename the original file "errata.prg" in "errata.zip", without doing anything else, you get a removable zip file with this inside:

[errata.zip](https://github.com/dirkwhoffmann/virtualc64/files/2293133/errata.zip)
![untitled 2](https://user-images.githubusercontent.com/34916641/44200584-3c3a3e00-a147-11e8-853d-78e45194420c.jpg)

**Comment by mortinus** [comment]
Good morning, any news about the solution of this problem?

**Comment by dirkwhoffmann** [comment]
Not yet.

Currently, I'm restructuring the VICII code which is pretty time intensive. The latest compatibility improvements came with a performance hit and I'm trying to get up to the old speed by optimizing the overall architecture. As a side effect, I'm trying to make the code easier to understand and therefore easier to maintain.

**Comment by mortinus** [comment]
Ruined Art run only on vice, strange message on screen ?!

![untitled 2](https://user-images.githubusercontent.com/41686391/44713413-55ca7680-aab3-11e8-8202-503e66a010d8.jpg)

**Comment by mortinus** [comment]
...nothing special in starion on vice

[starion.zip](https://github.com/dirkwhoffmann/virtualc64/files/2327359/starion.zip)
![untitled 4](https://user-images.githubusercontent.com/41686391/44713658-ddb08080-aab3-11e8-8e89-a6ae297a6deb.jpg)

**Comment by UgoCaneFifone** [comment]
This group of demo emulamers is a problem ...but I'd like to see them run on VirtualC64 !!!
Some "undocumented" CPU instructions that were once thought to have real random behavior have a well-defined behavior when the BA line rises just before the last instruction cycle, someone told me.

**Comment by dirkwhoffmann** [comment]
Didn't anybody report that some demo only runs in VICE when glue logic is set to "Custom IC"? I don't find any reference to that any more, but it's a smoking gun ...

**Comment by Alessandro1970** [comment]
There are too many conflicting news on the web.
David Horrocks managed to make the Ruined Art demo work in his HOXS and the only track is as follows:
**VIC phase 2 fetch fix for Ruined Art demo**
Then I found this:
 **SpriteEnableX fixed**
**Thinking about Emulamer, I just had to fix the "SpriteEnable"-Stuff (Sprites can have DMA turned on, but still they can be inactive). Vice 2.3 (normal Version) fails at some of those tests, we (and Vice SC) pass all now :)**
_(Sidenote: Ruined Art still not working...)_ 
We could start from here, from Ruined Art demo...

**Comment by Alessandro1970** [comment]
In addition to " VIC phase 2 fetch fix for Ruined Art demo ", David Horrocks confirmed to me by e-mail what he had written **above Ugo** that I had written to him (UGO/whatsapp) while I was on vacation and I had a lot of problems connecting.

This the aswer:
 _"One or more of the “undocumented” CPU instructions that were once thought to have random behaviour actual have a well defined behaviour in the case where the BA line goes high just before the last instruction cycle. I can not remember exactly which instructions needed to be to corrected but I believe the VICE test suite (not the Lorenz CPU test suite) does now test for the correct behaviour of these CPU instructions."_

![untitled 6](https://user-images.githubusercontent.com/34916641/44768942-49055b80-ab63-11e8-9274-79db166e3e5b.jpg)

**Comment by dirkwhoffmann** [comment]
I don't expect the problem being due to illegal opcode emulation. The VICE tests are passed. 

I think the problem is related to bank switching. The memory bank VICII sees is controlled by two CIA bits. When these bits change, the bank switches. However, there is some delay between switching the bits and the bank. Also, there is an interesting effect when a C64 with "Custom IC" glue logic is used. E.g., if the bits change from 01 -> 10 or from 10 -> 01, the 1 bits show up first. Hence, VICII sees memory bank 3 for one cycle. I'm pretty sure that this is the trick used by errata to get the correct graphics data. There must also be some effect when switching between banks 2 and 3 though, because this is what errata does when drawing the picture.

**Comment by Alessandro1970** [comment]
I tried the VICEsc, this morning, one way and another but the result does not seem to change
![untitled 10](https://user-images.githubusercontent.com/34916641/44770535-a354eb00-ab68-11e8-9415-37fe91f6ee95.jpg)

**Comment by Alessandro1970** [comment]
In the screenshot I sent you see the difference between Custom and Discrete.
Custom hangs and does not reveal the inscription "THE END"
![untitled 12](https://user-images.githubusercontent.com/34916641/44770928-d3e95480-ab69-11e8-8236-1bc1d22204f6.jpg)

**Comment by Alessandro1970** [comment]
The ERRATA demo at the 3° step writes: **This is the first trick in Ruined Arts...**

So Ruined Arts has that so called: "" **VIC phase 2 fetch fix for Ruined Art demo** ""
If Horrocks wrote the true the solution for these two demos is the finding related to _VIC phase 2 fetch fix_

![untitled 2](https://user-images.githubusercontent.com/34916641/44789695-8d155200-ab9d-11e8-80f9-69be39b0b06a.jpg)

**Comment by dirkwhoffmann** [comment]
"VIC phase 2 fetch".  Indeed, VICE has two fetch methods: 

    inline static uint8_t fetch_phi1(int addr) 

    inline static uint8_t fetch_phi2(int addr)

Graphics data is fetched in phase 1 and character data in phase 2. Sprite data is fetched in phase 1 or phase 2, depending on their DMA cycle. 

Right now, VirtualC64 doesn't care about the fetch phase.  Hot lead ...

**Comment by mortinus** [comment]
Is the problem an "Illegal opcode tweak" ?

**Comment by dirkwhoffmann** [comment]
Illegal opcodes are not the problem (in the failing demo part, no illegal opcodes are used). It's a timing issue (race conditions between the CPU writing a value into an I/O register and VICII picking up the value).

**Comment by dirkwhoffmann** [comment]
Just run Errata on VICE and compared the results of fetch_phi1(int addr) and fetch_phi2(int addr). Both functions always return the same value. Hence, the problem must be related to something else.

**Comment by mortinus** [comment]
...this demo tortures us! if could we find a solution ?

**Comment by dirkwhoffmann** [comment]
VICII performs several memory accesses. c-acceses, g-accesses, s-accesses and i-accesses (idle). c-accesses seem to be OK in VirtualC64. Next, I'll compare how g-accesses are handled in VICE ...

**Comment by dirkwhoffmann** [comment]
It seems that the demo is performing some tricky sprite collisions in the boundary area (around cycles 59, 60) at exactly the same time as the shift registers of the sprite are loaded with the three data bytes fetched in the DMA cycles. Therefore, several time constraints must be taken into account. 

I understand that some demo programmers are eager to write programs that are able to trick emulators and see this as a kind of competition. Since I really don't like cat and mouse games, the Emulamer team can get the trophy. Due to my limited time resources, I will continue to work on the VICE test cases, which seems more fruitful to me.

**Comment by dirkwhoffmann** [comment]
With a new day comes a new chance. By doing some standard code cleanup, I happened to see that the current implementation of VirtualC64 disables sprite collision detection outside the visible area even if the sprite sequencer is running. And indeed, we're coming closer ...

<img width="791" alt="ohne titel" src="https://user-images.githubusercontent.com/12561945/45602674-9ccddb00-ba65-11e8-8061-b2352b44ff92.png">

The result looks like if the picture we want to see is bitwise ORed with the random looking pattern.

**Comment by mortinus** [comment]
:+1:

**Comment by dirkwhoffmann** [comment]
Finally ...

<img width="791" alt="errata" src="https://user-images.githubusercontent.com/12561945/45801181-2c45e900-bd07-11e8-957e-41c08571ac1b.png">

There is still an issue with the glue logic stuff. Regardless of selecting "Custom IC" or "Discrete",  a CPU jam occurs at the end of the demo.

**Comment by Alessandro1970** [comment]
It also happens with the VICESC, I have tried repeatedly both with the PC version and with the MAC version and once the CPUJAM happens. Both with CUSTOM and DISCRETE, there is no certainty that it closes without error

**Comment by dirkwhoffmann** [comment]
"Both with CUSTOM and DISCRETE, there is no certainty that it closes without error"

OK, good to know. So it seems like I can close this issue 😃.

I am still working on cleaning up the code, because some of the recent changes slow down emulation. I.e., the sprite sequencer has to be executed in each and every cycle and not only in the cycles that belong to the visible screen.

**Comment by Alessandro1970** [comment]
Great result, for me this issue can be closed, given your excellent result.
Thank you

Ps. Ruined Arts works in you new version ?

**Comment by mortinus** [comment]
:+1:  :champagne:

**Comment by Alessandro1970** [comment]
Unfortunately, in recent reviews something has changed the results of the third part of this demo. Now a horizontal line appears too.
Is it possible to fix it again ?

<img width="844" alt="schermata 2018-11-16 alle 23 05 01" src="https://user-images.githubusercontent.com/34916641/48650043-00886c00-e9f5-11e8-98d4-87c6f41fa2b3.png">

**Comment by dirkwhoffmann** [comment]
Current findings:

Demo got broken with checkin d66c4e0e8b4cff4e01cfa818ee4da9520ca69c6c

Prviously, I had this in beginRasterline():

    // Prepare sprite pixel shift register
    for (unsigned i = 0; i < 8; i++) {
        spriteSr[i].remaining_bits = -1;
        spriteSr[i].colBits = 0;
    }

To get VICE test spritscan.prg to pass, I had to remove line 

      spriteSr[i].remaining_bits = -1;

But this causes the the green line to appear in the Errata demo.

Needs further investigation ...

**Comment by dirkwhoffmann** [comment]
Hard to see what's going wrong here. We need to rerun all sprite related VICE tests first, to see if something else got broken. The Donkey Kong Jr. bug could also be related to sprites ...

**Comment by rossimariolee** [comment]
Why don't you try to add the " spriteSr[i].remaining_bits = -1;" line again in the version alpha4/5 ?

**Comment by dirkwhoffmann** [comment]
Adding

    spriteSr[i].remaining_bits = -1;

is wrong as shown by VICE test spritscan.prg. There is another bug which was shielded before by resetting the remaining bits to -1.

**Comment by dirkwhoffmann** [comment]
Background: VICII has a shift register for each sprite containing the pixel data. Once activated, the existing VICII implementation runs the shift register for 24 cycles (because there are 24 pixels in a sprite). It seems that this is wrong and the shift register stops running when it's value matches 0 (this may take less than 24 cycles, but it may also take more than 24 when the register is loaded while running). If I read the VICE code correctly (not so easy), it seems like VICE is doing the same thing. From a computer engineering point of view, it's hard for me to image that this is really happening in a real VICII. If I had to design this chip, I would run it until the next load event happens, because this would require the least amount of glue logic. Anyway, I implemented it that way and it seems to fix this issue, as well as issue #474 (it doesn't fix #473 though): 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha9.zip

It'll be great if someone could confirm this and could run some other tests. Because a change to the VICII code is like an operation on the heart 😷, our "patient" may have suffered other damage in another place 🤒.

**Comment by dirkwhoffmann** [comment]
Alpha 10 most likely fixes #473 as well:

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha10.zip

**Comment by Alessandro1970** [comment]
All emulamer's demos work fine.
Great job!

**Comment by UgoCaneFifone** [comment]
It's ok for me too
