### ISSUE TITLE
"Krestage 3" Demo by Crest 50 Hangs

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#388]
"Krestage 3" Demo by Crest does not work, from a message about the impossibility of using Vic Tricks.
On the web I found this:
_The VIC emulation as been enhanced to include a 4 pixel delay before responding to 
changes to the sprite multicolor register. Stray pixels have been removed from the 
"Krestage 3" Demo by Crest 50 pixel sprite upper border._
[KRESTAGE3.D64.zip](https://github.com/dirkwhoffmann/virtualc64/files/2280035/KRESTAGE3.D64.zip)

VirtualC64:
<img width="783" alt="schermata 2018-08-11 alle 10 02 45" src="https://user-images.githubusercontent.com/34916641/43989642-84853946-9d4e-11e8-9d32-e601fbd8d43e.png">

Vice:
<img width="717" alt="schermata 2018-08-11 alle 10 04 48" src="https://user-images.githubusercontent.com/34916641/43989645-9ac6d0c0-9d4e-11e8-93ec-65dedfd62ad0.png">

**Comment by Alessandro1970** [comment]
50 pixels x-stretched sprites, 9 sprites in a row: great demo!
But is there a 50 pixel wide sprite or a 25 expanded ?

**Comment by dirkwhoffmann** [comment]
Don't know the details, yet. I tested V2.4 and V2.5 with the Darwin demo from 

https://csdb.dk/release/?id=12732

which also uses a lot of sprite effects. They seem to work well, so the CREST problem is not necessarily due to the handling of sprites.

I noticed that the Darwin demo flickers when showing the black text screens. It also flickers in VICE 3.1. I did not test it with VICE 3.2 yet, nor did I test it with Hoxs64. 

It'll be great to have a small program that tests if a real or a faked VICII is present (like the CREST demo does). The smaller the program the better. Perhaps, the CREST testing code is available somewhere as a stand alone program . If we can isolate the trick for testing for a real VICII, we can more easily track down the problem.

**Comment by Alessandro1970** [comment]
About the demo I have read this:

_Quote: HOXS 16 May 2007 v1.0.4.14 
===================== 
1) **Added 25 pixel sprite feature** used in the "Krestage 3" Demo by Crest. The demo will<br>
now run unpatched._

**Comment by dirkwhoffmann** [comment]
Is there any link to the applied code change? This would give us a valuable hint where the current incompatibility of VirtualC64 comes from.

**Comment by Alessandro1970** [comment]
[history.txt](https://github.com/dirkwhoffmann/virtualc64/files/2282821/history.txt)

**Comment by Alessandro1970** [comment]
This version of Krestage3 works fine on VirtualC64, probably the problem is another, not the sprites...

[krestage3-emufix.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2289501/krestage3-emufix.prg.zip)

<img width="782" alt="schermata 2018-08-15 alle 09 27 11" src="https://user-images.githubusercontent.com/34916641/44136574-914bd5dc-a06d-11e8-9159-e4636bef0901.png">

**Comment by dirkwhoffmann** [comment]
Thank you, that's good to know. So I guess, we simply fail the VICII test at the beginning of the demo.

**Comment by puleyo** [comment]
What kind of VIC-check is done?
Does VirtualC64 manage to pass the test?

**Comment by dirkwhoffmann** [comment]
No, it does not pass yet. Seems like they check for emulators explicitly which means that they most likely did all they can to make it difficult to track down the root cause. I simply don't understand these guys. What is the purpose of stealing other people's time? Anyway, it will just be a matter of time when this demo will run, too.

**Comment by mortinus** [comment]
I have seen that VIC-detection (of this demo) works in HOSX and VICESC, could someone tell us wich kind of detection is this ?

**Comment by UgoCaneFifone** [comment]
Maybe a Vic Timing check.
But looking at the (EMU)fixed version and the integral version: can you not see what kind of control has been eliminated ?

**Comment by puleyo** [comment]
I do not think it's a VIC / Timing problem but it could be some cheating related to the famous EMUFUXXOR (https://csdb.dk/release/?id=55745).
I would still like to see it resolved and know what it was.

**Comment by rossimariolee** [comment]
No, that is not EMUFUXX0R, that is a VIC/CHECK !
I would be resolved it too!
Does someone har tryied it on HOXS ? Does it fully works on HOXS ?

**Comment by Alessandro1970** [comment]
VICE.exe: DO NOT WORKS - HOSX WORKS
![untitled 2](https://user-images.githubusercontent.com/34916641/46734741-75e57c00-cc94-11e8-8cd7-ece642d23b83.jpg)

**Comment by Alessandro1970** [comment]
VICESC.exe and HOSX work but the has the same defect (number 3 out of the screen)
![untitled 6](https://user-images.githubusercontent.com/34916641/46734920-e42a3e80-cc94-11e8-8032-9a82d1e0c65d.jpg)

**Comment by dirkwhoffmann** [comment]
It's good to see that it works in vicesc. VICE has an excellent debugger, so it's possible to debug it the hard way:

1. Run VirtualC64 until the "No VIC inside" screen appears.
2. Hit "Rewind" and "Pause" immediately afterwards.
3. Open the debugger and see which address the CPU is at.
4. Start VICE and set a breakpoint to this address.
5. Step through the code in VirtualC64 and VICE in parallel until there is a difference. 

It's pretty boring though ☹️.

BTW, forget about vice.exe, always use vicesc.exe.

**Comment by dirkwhoffmann** [comment]
"(EMU)fixed version and the integral version"

What's the (EMU)fixed version? And what in the integral version? 🤔

**Comment by Alessandro1970** [comment]
Hi,
this is the original version with the VIC CHECK:
[krestage3-Integral.zip](https://github.com/dirkwhoffmann/virtualc64/files/2467415/krestage3-Integral.zip)

This is the "fixed" version for the emulators to which they have removed the initial "vic check":
[krestage3-emufix.zip](https://github.com/dirkwhoffmann/virtualc64/files/2467416/krestage3-emufix.zip)

**Comment by UgoCaneFifone** [comment]
I tried with the debugger but I can not understand anything.
I'm sorry, I hope that someone is more lucky or better than me to find the cause...

**Comment by dirkwhoffmann** [comment]
Woohoo 😎. With the ss-hires-mc-exp.prg bug fixed, VirtualC64 passes the VICII check: 

<img width="1274" alt="bildschirmfoto 2018-10-15 um 13 18 48" src="https://user-images.githubusercontent.com/12561945/46948384-3052f580-d07e-11e8-80ef-bda96ac228fe.png">

The VICII check is really mean (😖), because it relies on a very special interplay between the multicolor flipflop and the expansion flipflop when the mc bit changes in the middle of sprite drawing. Fortunately, the VICE team already figured this out. Still, understanding the VICE code is pretty tough in its own. 

Interestingly, VirtualC64 does omit displaying the "3" completely (I expected the output to be similar to VICE, because I adapted the VICE sprite sequencer logic). Pretty strange.

<img width="1274" alt="bildschirmfoto 2018-10-15 um 13 18 56" src="https://user-images.githubusercontent.com/12561945/46948619-fb936e00-d07e-11e8-9351-5d6eadb93e15.png">

**Comment by Alessandro1970** [comment]
Great!!!

The number 3, after few minutes, will be shown on the right, but it will be shown partially cutted.
This happens on VICESC and on HOXS !
VICE and HOSX:
![46734920-e42a3e80-cc94-11e8-8032-9a82d1e0c65d](https://user-images.githubusercontent.com/34916641/46949186-dc95db80-d080-11e8-8bf5-48033d8d96dc.jpg)


You can close the issue ! Thanks

**Comment by dirkwhoffmann** [comment]
"The number 3, after few minutes". Oh, thanks, I simply didn't run it long enough. Indeed, the "3" appears, and as expected, the graphics glitch is the same as in VICE (the grey dots are missing, because I used a 65x VICII (no grey dot bug)). 

<img width="1042" alt="bildschirmfoto 2018-10-15 um 13 57 08" src="https://user-images.githubusercontent.com/12561945/46949652-7316cc80-d082-11e8-83ef-38bf3c44481f.png">
