### ISSUE TITLE
Ruined Art hangs and shows the monitor automatically

### ISSUE THREAD

**Issue by puleyo** [dirkwhoffmann/virtualc64#411]
Ruined art hangs and shows the monitor automatically: is it an illegal opcode?
[ruined_art.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2342168/ruined_art.prg.zip)

<img width="1050" alt="schermata 2018-09-01 alle 10 20 16" src="https://user-images.githubusercontent.com/38581054/44944075-e74a2900-add0-11e8-9fe3-5f751772e0c8.png">

**Comment by rossimariolee** [comment]
It also stops on my mac in the same way and the monitor windows appears

**Comment by Alessandro1970** [comment]
**...for Ruined Art:**
_The VIC BA pin is connected to the CPU RDY pin and the CPU access the bus in the second phase of a system cycle. If the CPU was paused because BA was low and then the BA line transitions high in the clock before the CPU executes the last cycle of opcode $9F (AXA SHA) then the behaviour of opcode $9F is altered._
 
**The VICE testsuite checks for this behaviour here:**
svn://svn.code.sf.net/p/vice-emu/code/testprogs/CPU/sha

case AXA_ABSOLUTEY://SHAAY
case AXA_INDIRECTY://SHAIY AHX
    this->SyncChips();
    if (addr.byte.loByte < mY)
    {
        //page crossing
        axa_byte = (addr.byte.hiByte) & mX;
        addr.byte.hiByte = axa_byte;
    }
    else
    {
        axa_byte = (addr.byte.hiByte + 1) & mX;
    }

    if (((ICLKS)(CurrentClock - this->LastBAHighClock)) == 1)
    {
        axa_byte = mX;
    }

    WriteByte(addr.word, mA & axa_byte);
    check_interrupts1();
    m_cpu_sequence=C_FETCH_OPCODE;
    m_CurrentOpcodeAddress = mPC;
    m_CurrentOpcodeClock = CurrentClock;
    break;

**Comment by dirkwhoffmann** [comment]
<img width="791" alt="ruinedarts" src="https://user-images.githubusercontent.com/12561945/45862068-24984a00-bdc4-11e8-93df-e6a3d2d7108e.png">

**Comment by mortinus** [comment]
![happy-winking-eye-cartoon-face_xkvcxz_sb_pm](https://user-images.githubusercontent.com/41686391/45868774-f0eaff00-bd86-11e8-9703-6081d0c6e620.jpg)
