### ISSUE TITLE
Test case sprite y collision fails

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#421]
https://sourceforge.net/p/vice-emu/code/HEAD/tree/testprogs/VICII/spritey/

VirtualC64:
<img width="770" alt="schermata 2018-09-11 alle 23 21 23" src="https://user-images.githubusercontent.com/34916641/45388640-dc399900-b619-11e8-8ca2-ceffe42c00a2.png">

Vice:
<img width="716" alt="schermata 2018-09-11 alle 23 21 32" src="https://user-images.githubusercontent.com/34916641/45388653-e3f93d80-b619-11e8-82e4-a16df33bfa41.png">

**Comment by dirkwhoffmann** [comment]
Seems to be related to a sprite enable / disable issue. Hence, fix #424 first.

**Comment by dirkwhoffmann** [comment]
Was due to an error in compareSpriteY(). To switch DMA on or off, VICII only compares the lower 8 bits of the sprite y coordinate with the yCounter and not all 9 bits. Hence, 

    result |= (reg.current.sprY[i] == yCounter) << i;

has to be replaced by 

    result |= (reg.current.sprY[i] == (yCounter & 0xFF)) << i;

It does not fix the errata bug though.

<img width="791" alt="sprity" src="https://user-images.githubusercontent.com/12561945/45531101-64de5200-b831-11e8-93ee-5b204a647d49.png">
