### ISSUE TITLE
Video problems/Mojave

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#431]
Hi, I have installed Mojave just now...
VirtualC64 does not works for me:

<img width="775" alt="schermata 2018-09-29 alle 09 34 52" src="https://user-images.githubusercontent.com/34916641/46242649-8744a380-c3cb-11e8-8da9-1327a346c81b.png">

<img width="773" alt="schermata 2018-09-29 alle 09 35 13" src="https://user-images.githubusercontent.com/34916641/46242630-5f554000-c3cb-11e8-952e-e784b0b29de3.png">
<img width="1280" alt="schermata 2018-09-29 alle 09 36 26" src="https://user-images.githubusercontent.com/34916641/46242634-68dea800-c3cb-11e8-87fe-8585c5049737.png">

I cannot visualize all the screen

**Comment by dirkwhoffmann** [comment]
Did you test V2.5? V2.5 version works on my machine: 

<img width="978" alt="bildschirmfoto 2018-09-29 um 19 44 29" src="https://user-images.githubusercontent.com/12561945/46242724-390dbf80-c420-11e8-9c7a-5efe7c57961d.png">

But I have other major problems using Mojave. When I compile and run VirtualC64 from XCode, I get lots of beachballs and everything is very slow. It might be an issue with my file system though. I installed Mojave a couple of days ago and the "disk utility" already reports file system errors on snapshot 1. Apple, what are you doing to us 😖😠. Disappointing!

**Comment by Alessandro1970** [comment]
I use 2.6 wt

**Comment by Alessandro1970** [comment]
Later I will try 2.5

**Comment by dirkwhoffmann** [comment]
You can find a build of the current master branch here:

ww.dirkwhoffmann.de/virtualc64/VirtualC64_3.0_alpha1.zip

Hopefully, it works on your machine.

**Comment by Alessandro1970** [comment]
There is the same display issue:
<img width="803" alt="schermata 2018-09-29 alle 10 51 29" src="https://user-images.githubusercontent.com/34916641/46243535-be1fb700-c3d5-11e8-9f46-a34c9a2a80a1.png">

What is the DSA problem ?
<img width="793" alt="schermata 2018-09-29 alle 10 49 39" src="https://user-images.githubusercontent.com/34916641/46243548-d8599500-c3d5-11e8-8c8a-df28a37c84d6.png">

**Comment by Alessandro1970** [comment]
I have removed VirtualC64 and its preferences and reistalled again...the same error:
<img width="801" alt="schermata 2018-09-29 alle 10 54 49" src="https://user-images.githubusercontent.com/34916641/46243603-73eb0580-c3d6-11e8-9e94-77226b8577d9.png">

This is my MBP:
<img width="577" alt="schermata 2018-09-29 alle 10 54 18" src="https://user-images.githubusercontent.com/34916641/46243606-7cdbd700-c3d6-11e8-87e8-83463532255d.png">

**Comment by Alessandro1970** [comment]
...it seems that VirtualC64 on Mojave doesn't resize the image:
![schermata 2018-09-29 alle 11 06 06](https://user-images.githubusercontent.com/34916641/46243775-afd29a80-c3d7-11e8-94db-0067aff91fe1.png)
![schermata 2018-09-29 alle 11 05 57](https://user-images.githubusercontent.com/34916641/46243777-b4974e80-c3d7-11e8-89ea-6534eaa29f10.png)
<img width="807" alt="schermata 2018-09-29 alle 11 05 45" src="https://user-images.githubusercontent.com/34916641/46243778-b7923f00-c3d7-11e8-827e-55f6e25e5b49.png">

**Comment by puleyo** [comment]
I have the same problem on my macbook pro 2015.
More than half image is not more visible after installing Mojave.
:cry

**Comment by UgoCaneFifone** [comment]
The same thing on my MBP late 2014, ...Impossible to see the bottom of the c64 screen.

**Comment by Alessandro1970** [comment]
...and the dark mode isn’t so fine...
...normal more selected again !

**Comment by Alessandro1970** [comment]
I tryied on a mbp of a friend of mine, a 2015 with mojave and iris videocard: the same issue, the c64 screen is greater than the window, and changing the window dimensions Virtualc64 doesn’t resize well.

**Comment by dirkwhoffmann** [comment]
My own macbook seems to be the only one where VirtualC64 is running under Mojave:

<img width="265" alt="bildschirmfoto 2018-09-30 um 07 40 55" src="https://user-images.githubusercontent.com/12561945/46249361-891e6d80-c484-11e8-9bc3-9ab08a050d66.png">

Apple, how shall I debug this? 😠

**Comment by dirkwhoffmann** [comment]
Maybe it's related to this one (not sure yet):

https://stackoverflow.com/questions/52316783/nsscrollview-not-refreshing-its-document-view-in-mojave-osx-10-14

**Comment by mortinus** [comment]
😢  
MacBook Pro (Retina, 15-inch, Mid 2014) - MOJAVE
...VIRTUALC64 does not show images correctly, screen reduced to almost 1/4.

**Comment by mithrendal** [comment]
Having this too on a mac mini. Downloaded xcode project from github latest 3.0 alpha 1. Try to look into the sourcecode now as Dirk cannot reproduce it...

**Comment by dirkwhoffmann** [comment]
An important entry point is:

    override public func setFrameSize(_ newSize: NSSize) {
        
            super.setFrameSize(newSize)
            layerIsDirty = true
        }

Later, in func draw(_ rect: NSRect), layerIsDirty is queried:

    // Refresh size dependent items if needed
            if layerIsDirty {
                reshape(withFrame: frame)
                layerIsDirty = false
            }

Reshape(withFrame:) eventually calls reshape() which rebuilds the projection matrices etc.

    func reshape(withFrame frame: CGRect) {
    
        if let scale = NSScreen.main?.backingScaleFactor {
            
            var size = bounds.size
            size.width *= scale
            size.height *= scale
            
            metalLayer.drawableSize = drawableSize
            reshape()
        }
    }

Maybe, NSScreen.main?.backingScaleFactor returns NULL on your machines. In that case, reshape() would not be called 🤔

**Comment by mithrendal** [comment]
Oh thank you dirk. But too late.  It has fixed itself... so I cannot reproduce it on the mac mini. I had this half screen problem when I started the 3.0 alpha1 in Xcode. Then I did go to the xib file and played a little bit with autoresize on/off setting the height from 621 to 321 and back to 621 and then.... the problem was still there and then I dragged the edges of the c64 mainwindow  and then somehow it gave me the full c64 screen with the icons on the bottom (mhz, fps and so on). And when I start the V2.5 that one now also shows  absolutely normal. Everything finde now on my side. 

I would suggest that it has something to do with the sizing of the main window. All the other fellows could you please try to drag the top right edge to make the window smaller. Maybe that has fixed it somehow ...

**Comment by dirkwhoffmann** [comment]
Self-healing software. So cool 😎.

**Comment by dirkwhoffmann** [comment]
"My guess is: macOS does remember the size and the next time it starts with the last chosen size, even it is another version of VirtualC64. But somehow the old settings from high sierra got corrupted or misinterpreted."

Sounds reasonable to me. Actually, the VirtualC64 version should not matter, because the Metal code is more or less the same. I recommend using 3.0 alpha 1.

**Comment by mithrendal** [comment]
3.0 alpha 1
Something is still wrong on the mini. As I wrote above I managed to resize the main window in that way, that it looked normal and nice again. And it remembered the then choosen size and start position on the screen. So when I restart the V64 it would come nicely again in the same position with the same size and scaling.
Sounds good  so far. But there is still something wrong. When I enter the fullcreen mode then it does scale to the fullscreen. When I leave the fullscreen afterwards, it somehow has the wrong scaling in the metalview. It is far too big. So I reproduced the original problem again.  When I drag the size of the main window then it simply does not scale the metal view anymore, its like static and it will get clipped for that reason. This is good news because so we can find the real cause of the problem. Dirk did you tried to enter and exit fullscreen? Does your metal view still scale after leaving fullscreen? 
Have to look into it.

**Comment by Alessandro1970** [comment]
II tried to resize the VirtualC64 window in all the ways, or I tried to change the screen resolution from the settings menu, but nothing changes a part of the video remains outside the window and therefore can not be viewed. It could be a problem of centering and resizing, as if the coordinates of the window at the bottom right were no longer identifiable.
<img width="401" alt="schermata 2018-09-30 alle 09 54 32" src="https://user-images.githubusercontent.com/34916641/46254938-89743400-c497-11e8-82b0-9fb17b4b154c.png">

**Comment by Alessandro1970** [comment]
Strange also those black borders that appear after resizing the virtualc64 window:
<img width="825" alt="schermata 2018-09-30 alle 10 10 05" src="https://user-images.githubusercontent.com/34916641/46255076-1cfa3480-c499-11e8-9cbd-4bb17caaf03c.png">

**Comment by dirkwhoffmann** [comment]
VirtualC64 works perfectly on my machine, even in fullscreen mode 😫.

**Comment by mithrendal** [comment]
Don’t panic. We will get that right. I currently don’t have time. But maybe in the evening or tonight i will get some.

**Comment by mithrendal** [comment]
<img width="1515" alt="image" src="https://user-images.githubusercontent.com/17108995/46259342-8483a480-c4d8-11e8-9d2f-5d5141073fde.png">

I enabled @dirkwhoffmann  existing log output for 
`	NSLog("MetalLayer::reshape (%f,%f)", drawableSize.width, drawableSize.height);`

here is the log output sequence where I did the following actions:
1. ) I started a V64 in window mode which was not clipped and looked normal.
2.) I entered fullscreen, which looked normal
3.) I exited fullscreen and the metalview was drawn way too big, so that it got clipped at the half.

but the log shows at 3.) (2146.000000,1658.000000) the same as before in state 1.)
so there is no problem collecting the drawableSize. I also checked the three code fragments which dirk points us to but they seem to be ok.  I guess it must be later in the drawing process...

**Comment by mithrendal** [comment]
Ok I found the problem at the drawing code. Its in the metalsetup buildDepthBuffer() method. There are some optimizations which are problematic under mojave as it seems.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/17108995/46261065-eea74400-c4ee-11e8-93f9-5582ff5b2bcd.png">

I have out commented the problematic code and now it works like a charm.

**Comment by dirkwhoffmann** [comment]
Mithrendal, thanks a lot for debugging this! I'll fix the bug on the main branch asap and will also release a version 2.5.1 containing this fix.

**Comment by dirkwhoffmann** [comment]
2.5.1 should show up in "Check for updates ..." and solve the problem.

At first, I was worried if constantly rebuilding the depth buffer would hit performance, but everything feels smooth.
