### ISSUE TITLE
C64 configuration lacks in compatibility

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/virtualc64#440]
Hi, it seems to me that the C64 configuration is less compatible than the C64C !
If I use the c64 configuration the emulamers demos do not work fine, if I select the C64C configuration the emulamers demos work all and very well.
But in VICE emulamers demo work both in C64 pal and C64c configuration.
I think that C64C configuration is ok but the C64 one is missing something.

**Comment by dirkwhoffmann** [comment]
Please be more specific about the broken emulamer demo. I need some specific test case to work on.

**Comment by Alessandro1970** [comment]
Hi,
I have found these differences between the C64 breadbin standard configuration and the C64C Pal version (I do not show the images obtained with the C64C configuration because it works):

Emulamer Errata shows letters in demo part 2 (upper part of the screen)
<img width="805" alt="schermata 2018-10-07 alle 09 40 13" src="https://user-images.githubusercontent.com/34916641/46579612-85a35d00-ca15-11e8-8959-6e9a7f2a91d7.png">
<img width="801" alt="schermata 2018-10-07 alle 09 40 37" src="https://user-images.githubusercontent.com/34916641/46579613-8b993e00-ca15-11e8-9949-8c1efc3d7bd1.png">

**Comment by Alessandro1970** [comment]
Emulamer Undead Demo does not show vertical writing in motion
<img width="791" alt="schermata 2018-10-07 alle 09 49 36" src="https://user-images.githubusercontent.com/34916641/46579663-7244c180-ca16-11e8-927b-74a4530a8812.png">

**Comment by Alessandro1970** [comment]
Ram Bo Demo and Conclusion Demo work well on both configurations, I can not find other differences for the default C64 Breadbin configuration.
...but the letters that appear and disappear writing EMULATION FAILURE in the CONCLUSION demo can only be seen in the initial part with the default configuration C64 Breadbin while in the most compatible C64C are not seen at all even if everything else works.
Emulamer Conclusion, Flashing letters in the first part after the written "USE 6569":

<img width="803" alt="schermata 2018-10-07 alle 09 54 58" src="https://user-images.githubusercontent.com/34916641/46579725-57bf1800-ca17-11e8-937e-81abf534cf57.png">

**Comment by dirkwhoffmann** [comment]
We need to check if they work in VICE and Hoxs64 with the selected configurations. I'll check when I've got some more time...

**Comment by Alessandro1970** [comment]
Emulamer tests are not so basic and do not always work true C64 ...
@rossimariolee But if you want to see them all use the most compatible "Custom Configuration", in this way I can see all the Emulamers's with the VirtualC64 3 beta 2 without problems:
<img width="561" alt="schermata 2018-10-07 alle 10 09 11" src="https://user-images.githubusercontent.com/34916641/46579830-4aa32880-ca19-11e8-8a35-acf2ac86364a.png">
I use always this configuration !

**Comment by Alessandro1970** [comment]
With the new version 3.0 beta 2 all Emulamers Demos can be seen with this configuration that is reported in the image, but you will not see the letters that disappear in the CONCLUSION demo after the writing USE 6569 because they can be seen only if you replace the 8565 chip with the 6569 R3, but that would imply the malfunction of the demos.
<img width="557" alt="schermata 2018-10-07 alle 11 07 18" src="https://user-images.githubusercontent.com/34916641/46580254-90fc8580-ca21-11e8-938d-8a4eb8612e40.png">

**Comment by rossimariolee** [comment]
Ok, I have tryied the words in demo Conclusion after “USE 6569” can be seen only with 6569 r3 the other chip cannot visualize them. Why? Are there some instruction that work only in 6569 ?

**Comment by dirkwhoffmann** [comment]
Many demos are so sophisticated that they only work with specific hardware configs. Please only report failing demos that work in VICE and do not work in VirtualC64 when the exact same hardware profile ist used. The first six VICE profiles are the same as the ones provided by VirtualC64.

"if you can enable the Gray Dot also with the 6569R3". The original intend of letting the user switch bugs on or off was to give him the ability to switch a bug off, not on 😉.

**Comment by dirkwhoffmann** [comment]
BTW, 3.0 beta 4 is out. Compared with beta 3, it does not improve compatibility, but fixes a severe bug that could cause the emulator to crash when loading a snapshot file. (For one variable in the Drive class, I was accidentally storing a pointer to a stack variable and this variable is obviously no longer there when a snapshot is read. Hence, whenever reading a snapshot, an unowned memory cell is written and it's pure luck when it loads correctly).

**Comment by dirkwhoffmann** [comment]
"If you select it from another MOS and then change it turns gray but remains selected."

When the option is grayed out, it has no effect (no matter if the box is checked or not).

**Comment by mortinus** [comment]
ok: (no matter if the box is checked or not).

**Comment by Alessandro1970** [comment]
VirtualC64 3.0 beta 4 has great compatibility.
Thanks

Note: 6569 hidden messages from Emulamers are seen only by MOS6569 users...
For this reason one has to selec only MOS6569 !

**Comment by rossimariolee** [comment]
ok
