### ISSUE TITLE
Window Roms Dialog button

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#463]
Hi,

is it possible to add a button in the Hardware Config Window to display the Roms Dialog Window ?

Note: to change the roms to try JaffyDos I had to rename the roms folder (so the VirtualC64 was going to ask for new Roms), but a button in the hardware config (to display the Roms in use) will be faster and more simple.

**Comment by dirkwhoffmann** [comment]
In V3.2, it'll be easier to replace a ROM, e.g., to install JiffyDOS.

Open menu item "VirtualC64->Preferences->ROM images" which displays a redesigned ROM dialog:

<img width="465" alt="bildschirmfoto 2018-11-19 um 13 00 15" src="https://user-images.githubusercontent.com/12561945/48706089-63e3eb00-ebfb-11e8-9352-5865be226b25.png">

Click the trash icon for the Kernal Rom:

<img width="465" alt="bildschirmfoto 2018-11-19 um 13 00 33" src="https://user-images.githubusercontent.com/12561945/48706108-778f5180-ebfb-11e8-90e1-93a9a199cdfc.png">

Drag in JiffyDOS, click OK, and perform a reset.
<img width="1034" alt="bildschirmfoto 2018-11-19 um 13 04 14" src="https://user-images.githubusercontent.com/12561945/48706148-a86f8680-ebfb-11e8-8b8c-d8f58addda55.png">

**Comment by Alessandro1970** [comment]
Great and very easy !

**Comment by dirkwhoffmann** [comment]
Support is available in 3.2 alpha 4: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha4.zip

Any feedback is welcome.

**Comment by Alessandro1970** [comment]
It works fine, thanks !

**Comment by mortinus** [comment]
Ok, it works but why not a button here:
<img width="552" alt="schermata 2018-11-19 alle 23 35 40" src="https://user-images.githubusercontent.com/41686391/48739303-da143c00-ec53-11e8-9b3d-5d371d5c8f80.png">

**Comment by dirkwhoffmann** [comment]
Good idea, Mortinus! I'll a button in the hardware preferences.

**Comment by dirkwhoffmann** [comment]
Button is available in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha6.zip

The new implementation computes fingerprints for all ROMs (simple FNV-1a hash values) and can therefore recognize different ROM revision. This might be useful especially for the Kernal Rom, because there are three different revisions (the third being the most common one):

<img width="477" alt="bildschirmfoto 2018-11-22 um 10 53 58" src="https://user-images.githubusercontent.com/12561945/48895518-8b2df880-ee45-11e8-8c36-d711ffab80b2.png">

If you replace the Kernal by, e.g, JiffyDOS, it looks as follows: 

<img width="477" alt="bildschirmfoto 2018-11-22 um 10 54 17" src="https://user-images.githubusercontent.com/12561945/48895537-997c1480-ee45-11e8-9b3d-643755325f4e.png">

If we want to, we can add JiffyDOS to the known ROMs. There is a simple array map in file RomPrefsController.swift:

    let knownKernalRoms : [UInt64 : String] = [
        0x0000000000000000:
        "This 8 KB Rom contains the low-level operating system. There are three major revisions of this chip, the third being the most common.",
        0xFB166E49AF709AB8:
        "Commodore 64 Kernal (1st revision)",
        0x4232D81CCD24FAAE:
        "Commodore 64 Kernal (2nd revision)",
        0x4AF60EE54BEC9701:
       "Commodore 64 Kernal (3rd revision)",
        0x429EA22675CAB478:
        "Commodore 64 Kernal (3rd revision, Danish)",
        0x8C4548E2202CB366:
        "Commodore SX-64 Kernal",
        0x746EB1BC008B07E1:
        "Commodore SX-64 Kernal (Scandinavian)",
    ]

BTW, is it "ROM" or "Rom"? 🤔 I'm somewhat inconsistent on this.

**Comment by Alessandro1970** [comment]
...I prefer "ROM", by the way it works well we can close...

**Comment by mortinus** [comment]
It works fine for me too
