### ISSUE TITLE
Open a Disk Image from menu crashes VirtualC64 (Only in alpha release)

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#464]
Hi, 
if I try to open a disk image from the menu (FILE --> OPEN --> .d64 image) the VirtualC64 crashes.

This is the report of the crash : 
[report.txt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2578330/report.txt.zip)

<img width="746" alt="schermata 2018-11-13 alle 23 03 28" src="https://user-images.githubusercontent.com/34916641/48446149-cae74700-e798-11e8-8746-58058be1c9b1.png">

**Comment by mortinus** [comment]
It crashes on my mac too. (alpha 4)

**Comment by rossimariolee** [comment]
If "Open" is selected from menu and than you try to load a .d64, a .crt or a .tap image VirtualC64 (alpha 4) quit immediatly.

**Comment by dirkwhoffmann** [comment]
Found it. When the emulator starts, macOS calls the following methods (besides others):

    awakeFromNib()
    windowDidLoad()
    windowDidBecomeMain()

Originally, the AudioEngine was initialized in windowDidLoad and used in windowDidBecomeMain. However, it seems that the function order may vary. I.e., if a second window opens, the following order is possible: 

    awakeFromNib()
    windowDidBecomeMain()
    windowDidLoad()

Hence, the AudioEngine is used before it is initialized which crashes the emulator. 

It didn't crash in 3.1.1, because AudioEngine initialization was still implemented in Objective-C. I notices that a couple of weeks ago and migrated it to Swift (with the bug included). 

I've  moved to initialization to awakeFromNib() which seems to a safe place. The crash should be gone in alpha 5:

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha5.zip

BTW, I assembled together a small tutorial how to get debug information in Xcode when the emulator crashes. Sometimes (as in this case), the crash report alone does not contain enough information to debug. The tutorial (which shows how to debug the bug we're talking about) is available on GitQ in the forum:

https://gitq.com/dirkwhoffmann/virtualc64/topics/8/how-do-i-report-a-crash

If you are eager to walk through the tutorial and think that it's not clear enough at some point, please let me know.
