### ISSUE TITLE
Courbois TURBO-DISK

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/virtualc64#467]
Hello,
Could you add the support for this cartridge ? Please 

[Courbois_Disk-Turbo.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2591646/Courbois_Disk-Turbo.crt.zip)

![courbois_disk-turbo_bottom](https://user-images.githubusercontent.com/41686391/48659688-758b8e00-ea55-11e8-892f-c37da32cf209.jpg)
![courbois_disk-turbo_top](https://user-images.githubusercontent.com/41686391/48659802-c9e33d80-ea56-11e8-94b0-f76b2084d87f.jpg)

Comparison: (on loading 150 blocks)
1541 normal  		- 100 seconds
micropower 2000 	-  48 seconds
CBM 4040 Dual Drive 	-  20 seconds
1541 with **Courbois DISK-TURBO** 	-  19 seconds

**Comment by dirkwhoffmann** [comment]
The cartridge seems to be a standard cartridge and the intro screen shows up correctly when plugged into VirtualC64. However, the fast loader seems to be incompatible with the current drive emulation. Did you check if it works in VICE?

**Comment by Alessandro1970** [comment]
In the VirtualC64 alpha 4 it works fine

<img width="828" alt="schermata 2018-11-19 alle 22 49 30" src="https://user-images.githubusercontent.com/34916641/48737116-7ab32d80-ec4d-11e8-8b94-8dbbfe9f7e13.png">

**Comment by mortinus** [comment]
In virtualC64 alpha 4 works fine, the switch is only for disable the cartridge (On/off)

**Comment by rossimariolee** [comment]
Ok, it works fine

**Comment by UgoCaneFifone** [comment]
It works for me, thank you. 
It's "fast" like the Epyx FastLoad...

**Comment by Alessandro1970** [comment]
I did some "do it yourself" tests with a simple stopwatch in my hand and apparently there is a slight improvement in loading (4/5 seconds ...)
... I do not think they sold a lot of these cartridges ...
We can also close ... (... thinking about the AR 7.5... :smile:  )

**Comment by dirkwhoffmann** [comment]
For me, it doesn't work ☹️:

<img width="973" alt="bildschirmfoto 2018-11-20 um 18 03 15" src="https://user-images.githubusercontent.com/12561945/48790091-d8e41d00-ecee-11e8-8164-e8c2550af0df.png">

<img width="973" alt="bildschirmfoto 2018-11-20 um 18 05 03" src="https://user-images.githubusercontent.com/12561945/48790093-daade080-ecee-11e8-9983-ec2860929101.png">

**Comment by dirkwhoffmann** [comment]
Actually, we never checked if we all use the same ROMs, i.e., the same VC1541 ROMs 😳😲.

I'll modify the ROM dialog in a way that it displays a fingerprint for the installed chips. I need to do this anyway, because I wanted to add some textual description for known Roms. E.g., a JiffyDOS Kernal could be named as such in the ROM dialog.

**Comment by Alessandro1970** [comment]
I tried another time just now.
It works for me, also with alpha 5:
<img width="801" alt="schermata 2018-11-20 alle 22 38 21" src="https://user-images.githubusercontent.com/34916641/48804500-1491dd80-ed15-11e8-8fbd-963960a5dd3a.png">

**Comment by Alessandro1970** [comment]
ah sorry ...I use this 1541 rom: 1541-II.355640-01.bin

**Comment by dirkwhoffmann** [comment]
I tested a couple of files with mixed results.

When I load a directory or a small game (such as Juice or Boulder Dash), it seems to work. When I load a bigger file, e.g., International Karate (IK) or Goonies, I get a CPU Jam. International Karate loaded well in VICE, but Goonies did Jam the VICE CPU, too.

Based on this experiments, I think it does not make sense to debug this further. The reason for the IK CPU jam might indeed be due to limitations of the current drive implementation, but this cartridge is not a suitable test case for finding them. 

I think it's best if we close this issue for now.
