### ISSUE TITLE
Unified preferences window (tabs)

### ISSUE THREAD

**Issue by michellekg** [dirkwhoffmann/virtualc64#482]
So, how about combination of all settings in one window but on different tabs? You know, like system settings or settings in many other apps. And if possible lets assign a familiar shortcut to settings - Cmd+, (Cmd + comma).

**Comment by dirkwhoffmann** [comment]
I though about merging all preferences windows myself a couple of times. Eventually, it might be a good idea to do so. I didn't do it yet, because it's a lot of work and I was simply unsure if it's a good idea. I propose to first assemble some mockup in Interface builder to get a feeling about the consequences.

If a tab based preferences window is implemented, the following dialogs could be merged into one: 

- Rom preferences
- Devices preferences (Joystick, Mouse)
- Video prereferences
- Emulator preferences (maybe renamed to 'Misc'?)
- Hardware preferences
- Keymap (the one which opens when you select menu item  "Keyboard -> Customize Key Map ...")

Hence, the tabs could be: 

    Roms | Hardware | Video | Emulator | Devices | Keymap

Advantages: 
- This approach would fit well with Mortinus' request #483. Instead of just saving the video settings, all settings in the tabbed dialog would be saved to a config file. 

- It is clear which dialog should open when Cmd+comma is typed (there is only one).

Disadvantages: 
- The new dialog would be a bloated elephant, at least implementation wise.

**Comment by Alessandro1970** [comment]
Tab based preferences is a good idea, the need to save (whit name file) the user’s choices ...a good idea too.

**Comment by puleyo** [comment]
Good the TAB based preferences, like LibreOffice !
Save different preferences file is good, so we can create a "user file preference configuration" for demos ...one for games ...one for GEOS and so on...

**Comment by michellekg** [comment]
Nice idea.

**Comment by dirkwhoffmann** [comment]
Up and running:

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha3.zip

Hit Cmd + comma to open the new dialog (or use the toolbar icon).
