### ISSUE TITLE
Snapshot periodicity changes only on loss of focus of periodicity field

### ISSUE THREAD

**Issue by tsupplis** [dirkwhoffmann/virtualc64#492]
Hi Dirk,

The periodicity if snapshot enabled stays at 3 seconds.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/11035456/50343207-ef63db00-051d-11e9-9616-ff3c1bf0f800.png">

To Reproduce
- Open Emulator Preferences (The value is the default aka 3)
- Enable snapshots
- Set to a value to 10 
- Press ok
- Reopen preferences 

The value is still the previous aka 3

What works is:

To Reproduce
- Open Emulator Preferences (The value is the default aka 3)
- Enable snapshots
- Set to a value to 10 
- Change the focus on another field in the preference dialog
- Press ok
- Reopen preferences 

The value is now 10

**Comment by dirkwhoffmann** [comment]
Thanks! I already know how to fix it, because I had the same problem with the text fields in the emulator preferences. An ordinary NSTextFields only triggers it's action function when return or tab is hit. However, these elements can be configured to update their contents continuously which does the trick.

**Comment by dirkwhoffmann** [comment]
Should be fixed in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha5.zip

Please reopen if there are any issues left.

**Comment by dirkwhoffmann** [comment]
Mission complete. Sneaked into SourceForge, shamelessly grabbed all their code and went out. Didn't even say good bye 😎. 

I've already done some comparison. The new reSID version can be integrated easily, because there are only a few changes. They did work on the reset behaviour, so there is a real chance that they fixed the bug we're talking about in this thread. 

<img width="1043" alt="screenshot 2018-12-21 at 15 59 51" src="https://user-images.githubusercontent.com/12561945/50349953-bd627100-053d-11e9-8f17-0422ab2f5f82.png">

They also changed some calculations, so the new version might sound different, too.

<img width="779" alt="screenshot 2018-12-21 at 16 01 05" src="https://user-images.githubusercontent.com/12561945/50349988-dec35d00-053d-11e9-8b93-d3e365e38d18.png">

There are more changes in the envelope generator ...

Stay tuned ...

**Comment by tsupplis** [comment]
Works well.
