### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#496]
I find the running the same demo in VICE/Virtual 64 that volume is much higher in VICE.
Possible to add volume control?

**Comment by Alessandro1970** [comment]
Hi, I think it would be very useful to insert a volume icon with "slider" and put this icon in the tool bar to allow a quick change of the volume.
I mean an icon that shows something like this photo:
<img width="60" alt="schermata 2018-12-26 alle 09 37 20" src="https://user-images.githubusercontent.com/34916641/50439383-2eb17380-08f2-11e9-9c65-0e4916324778.png">

**Comment by dirkwhoffmann** [comment]
Why add a volume control when the Mac already has one? I think it's more Appleish if we simply calibrate the VirtualC64's sound engine to mimic the Mac's standard volume and let the Mac slider do the job. The only problem is to find out what the default should be. Maybe there are some Apple guidelines, I don't know. The brute-force way would be: 

1. Play some sound with "standard volume" set (iTunes doesn't help, because it has a separate slider). Maybe reading a text out load via VoiceOver ...
2. Find  a C64 game which sounds like it uses the "default volume" on the C64 (be aware that SID has it's own volume register). 
3. Adjust the scaling factor inside to SID code to match the Mac volume.

**Comment by Alessandro1970** [comment]
In fact I noticed that increasing the volume of the Mac at most does not feel very good (we do not hear much ... we are old ... hearing falls ...  😢  ), a slider on the bar to adjust the output of the VirtualC64 could have been useful. 
Maybe option 3 could be the best, sometimes it would not be bad to push the volume of the commodore64 as much as you could with the television 😃

**Comment by UgoCaneFifone** [comment]
Oh yes, how we can increase the brightness of the VIC would be a good thing to increase the volume of the SID, even on my MBP is a little low and does not always feel good.

**Comment by dirkwhoffmann** [comment]
I've increased the default volume in 
http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha7.zip

I still don't understand why I need two volume controls. For me, this would only make sense if there were several sound sources whose volume had to be adjusted *relative* to each other. But the emulator has only one source. I like to admit that the preset volume was quite low, especially in direct comparison with VICE.
