### ISSUE TITLE
VirtualC64 crashes while closing

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#505]
Hi,

sometimes VirtualC64 crashes while closing, I do not know why: after play I only quit it pressing the red circle button in the corner and than closing the VC64 without saving.
here is the report:

[reportVirtualC64.txt](https://github.com/dirkwhoffmann/virtualc64/files/3123685/reportVirtualC64.txt)

**Comment by dirkwhoffmann** [comment]
Presumably fixed in V3.3.1 beta 1: 

http://dirkwhoffmann.de/virtualc64/VirtualC64_3.3.1b1.zip

Areas to focus testing on: 

- Mouse behaviour (internal coordinate handling has changed)
- Behaviour when closing a window (does it still crash?)
- Audio (AudioEngine shutdown behaviour has changed) 
- Toolbar input device settings (user default storage handling has changed)

**Comment by Alessandro1970** [comment]
Hi,
Great! 
It works fine, it does not hang on exit and the mouse works well in Geos !
Thanks

<img width="783" alt="Schermata 2019-05-01 alle 11 17 37" src="https://user-images.githubusercontent.com/34916641/57011626-e806b980-6c02-11e9-8625-6fe0a1c7997d.png">

**Comment by dirkwhoffmann** [comment]
Version 3.3.1 is now available via the update server.
Please reopen if the problem occurs again.
