### ISSUE TITLE
New CRT-test from Vice Team

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#508]
Hi,
as can be read from their site:

> _paltest: demonstrates the mix colors created by pal en/decoding.
> 
> emusux0r-crest: demonstrates the "black bleeding" effect created by the nmos
> output stages_.

https://sourceforge.net/p/vice-emu/code/HEAD/tree/testprogs/crtemulation/

[emusuxX0r-crest.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/3145253/emusuxX0r-crest.prg.zip)
![c64_emusux0r](https://user-images.githubusercontent.com/34916641/57190441-6bcde800-6f1a-11e9-8ba9-48db01dd49fa.png)

**Comment by mortinus** [comment]
Hello everyone !
Even if I remove the graphic filters and change the VIC, something is glimpsed but I don't read well and  clean !
Do we need a CRT TV to see this effect or even the ViceEMU shows such a clear result ?

**Comment by Alessandro1970** [comment]
Mortinus, you're probably right!
The image I posted was taken **from the VICE website**.
While instead I took **this from the VICE emulator** directly:
It seems to me that VirtualC64 behaves in the same way !

![Untitled 2](https://user-images.githubusercontent.com/34916641/57362618-881e8e80-717f-11e9-9008-911b2c5216d3.png)

**Comment by dirkwhoffmann** [comment]
We need to find out what "pal en/decoding" means. Seems to be a cool Crest demo.

**Comment by dirkwhoffmann** [comment]
http://hitmen.c02.at/temp/palstuff/

"This effect was attributed to the NMOS output drivers in the past, but that has been proven wrong - C64s that have their RF-Modulator removed do not show this artefact, which means it is produced by the circuit in the RF-Modulator. It can be roughly described by the following rules:
when going from high to low, the transition is relativly fast (about 0,5 pixels) because the line is activly pulled low.
when going from low to high, the transition is relativly slow (about 2 pixels) because the line is just "left alone" which causes it to go high.
This has the consequence that in high resolution patterns with high contrast between the pixels (eg black and white) the actual hires pixels will never be able to reach their intended full brightnes and turn out darker, and infact smaller, than they should."

**Comment by Alessandro1970** [comment]
...so we can close this

**Comment by dirkwhoffmann** [comment]
Nooo, don't close. We could try to emulate the effect on the GPU and offer it as an option in the video settings.

**Comment by dirkwhoffmann** [comment]
Actually, this effect has turned out to be quite tricky (despite the simple physical background). To make it look right, it has to be calculated with the GPU. However, this is not as easy as it might seem. The problem is that the effect is hard to parallelize: to calculate the pixel in column n, the shader needs to know the value in column n-1 and so on. I guess a multi-pass shader would be required.

If the effect is emulated directly on the emulator texture via the CPU, the standard screen looks like this: 

<img width="722" alt="Screenshot 2019-05-14 at 17 29 41" src="https://user-images.githubusercontent.com/12561945/57711445-06db6600-766f-11e9-9114-df98c8c113e0.png">

In fact, the Crest text becomes visible to some extent, but not on a still image (it requires the flickering animation implemented in the demo).

All in all, I now doubt that the effort for the implementation is worth it. Maybe it is better to concentrate on Amiga stuff instead.
