### ISSUE TITLE
Buttons on MacBook touch bar don't work with shift key

### ISSUE THREAD

**Issue by wulab** [dirkwhoffmann/virtualc64#509]
Hi,

Today I try Virtual C64 version 3.3.1 on my MacBook Pro 2016 with touch bar (macOS Mojave). It is marvellous to see custom buttons in there! However, they don't work with shift key. For example, holding the shift key and pressing the RUN/STOP button doesn't RUN my program. Selecting the Shift Lock option from menu bar doesn't help either as it will do a LOAD instead.

Also, I can't clear the screen by pressing shift + CLR/HOM button while it is working fine in the keyboard emulation.

**Comment by dirkwhoffmann** [comment]
Thanks a lot for reporting! I have to admit that I haven't tested the Touch Bar buttons for a longer time. I will try to fix them in 3.3.2.

**Comment by wulab** [comment]
@dirkwhoffmann Thanks! Looking forward to it.

**Comment by DannyCork** [comment]
oh, I never knew there were custom touchbar buttons. Bravo !

**Comment by dirkwhoffmann** [comment]
The Touch Bar keys should work again:

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3.2b1.zip

Could you give it a try? 

I took the chance and cleaned up the Touch Bar code a little bit. The images are now "template images" (Apple's proposed method to handle colour mode independent black and white images). This fixes the issue with the time travel Touch Bar keys which were drawn in black instead of white.

**Comment by dirkwhoffmann** [comment]
V3.3.2 is available via the update server.

Please reopen if you encounter another Touch Bar issue. Thanks again for reporting!
