### ISSUE TITLE
Keyboard mapping problems

### ISSUE THREAD

**Issue by sdsnatcher** [dirkwhoffmann/virtualc64#527]
After having issues with some drawing apps, I've run [this keyboard test](https://csdb.dk/release/?id=98411) to check if the keyboard mapping had problems. And indeed it has. 

Many keys are not mapped, requiring the virtual keyboard to be used all the time. But, sadly, that's very unproductive.

1) Symbolic keyboard mapping missing keys
- ← key: ESC seems to be the perfect candidate
- SHIFT: The respective SHIFT keys are the best candidates
- CTRL is mapped to TAB: but this is awkward, since C64 programs will state "Press CONTROL for doing x". So a better symbolic mapping should be CONTROL too
- RUN/STOP: The best candidate seems to be TAB
- ↑ key: Map to page-up (FN+UP on compact keyboards)
- CLR/HOME: Map to F9
-  RESTORE: Map to F10

2) Positional keyboard mapping missing keys

- £ key: F2 could be a good candidate
- CLR/HOME: F9 could be a good candidate
- ↑ key: Map to page-up (FN+UP on compact keyboards)
- ← key: I can't remap this to the ESC key, since it closes the keyboard remap screen
- It would be nice to be able to map both the UP/DOWN key to both UP and DOWN keys of OS-X. Same deal with LEFT/RIGHT and LEFT and RIGHT keys.
- I couldn't find the RESTORE key on the key assignment screen to try to assign it to some other key. Also, a good default assignment for this key could be F10 again.

3) SHIFT LOCK emulation

[This thread](https://csdb.dk/forums/?roomid=11&topicid=98819) explains how the SHIFT/LOCK key can be detected

But I'm not sure if the Eastline keyboard tester uses that trick.

After it's emulated, CAPS-LOCK would be the best natural mapping.

**Comment by dirkwhoffmann** [comment]
Thank you for this extensive list! I'll see what I can do. 

It won't be possible to realise all of your suggestions though, mostly because of the way symbolic mapping works: 

- If symbolic mapping is selected, I cannot map, e.g., the Shift keys. This is because on some keyboards, you have to press Shift to get '<' (e.g., on US keyboards). On others, this character is available directly (e.g., on German keyboards). The same holds for the other auxiliary keys. This is the reason why I've added "positional mapping" as an alternative. 

- The RESTORE key has no key code, because it is directly wired to the NMI line of the CPU. Because of that, VirtualC64 cannot handle the RESTORE key as a real key internally.

- I don't want to map the ESC key, because it is used for many Mac activities (closing full screen, closing dialogs). 

Maybe, I can map the C64 left arrow key and the C64 down arrow key to FN-LEFT and FN-DOWN. However, this only works in symbolic mapping if FN-LEFT and  FN-DOWN produce a recognisable character that is independent of country specific keyboard layouts.

Mapping the C64 keyboard to a modern keyboard is really hard. The Amiga is much easier in this respect.

**Comment by sdsnatcher** [comment]
> If symbolic mapping is selected, I cannot map, e.g., the Shift keys. This is because on some keyboards, you have to press Shift to get '<' (e.g., on US keyboards). On others, this character is available directly (e.g., on German keyboards). The same holds for the other auxiliary keys. This is the reason why I've added "positional mapping" as an alternative.

Are you sure? Because the openMSX emulator has the same problem/solution for the MSX computer, and emulates the SHIFT key normally. Same deal with [webMSX](http://webmsx.org), as this one runs in Javascript inside the browser.

> The RESTORE key has no key code, because it is directly wired to the NMI line of the CPU. Because of that, VirtualC64 cannot handle the RESTORE key as a real key internally.

But can't it be emulated as a special (aka fake) key? IOW, it would appear in the key remapping screen, but the emulator would know that it needs to have a special handler instead of generating a keycode.

> I don't want to map the ESC key, because it is used for many Mac activities (closing full screen, closing dialogs).

Most emulators implement the full-screen switching with CMD+F and/or OPTION+ENTER. This would solve this problem, since inside the dialogs you can't send any other keys to the emulated C64 anyway.    :)

**Comment by dirkwhoffmann** [comment]
> this only works in symbolic mapping if FN-LEFT and FN-DOWN produce a recognisable character that is independent of country specific keyboard layouts.

Hitting FN-UP on a MacBook translates to PageUp and FN-DOWN to PageDown. I've just extended the symbolic key map to assign FN-UP to the C64's up arrow key and FN-DOWN to the C64's left arrow key. I cannot map FN-LEFT to the left arrow, because FN-LEFT maps to the home key. 

In v4.0, editing the positional keymap will be more user friendly, i.e., the user is no longer confronted with the internal C64 keyboard matrix. As a side effect, the RESTORE key (which is not part of the keyboard matrix) will be mappable, too.

<img width="758" alt="Bildschirmfoto 2020-09-06 um 13 10 02" src="https://user-images.githubusercontent.com/12561945/92324822-7421c000-f045-11ea-8143-37a82ab13c22.png">
