### ISSUE TITLE
Drastic slowdown when installing a Rom file

### ISSUE THREAD

**Issue by rcoenen** [dirkwhoffmann/virtualc64#532]
Version 3.3.2 (3.3.2)

When I drag any of the 4 ROMs onto the preferences panel (see below) then they just "bounce back" to their original location. I cannot get the installation of the ROMS to work.

![image](https://user-images.githubusercontent.com/753704/63645469-dcb52d80-c6cc-11e9-8c88-b73e0bfd2a47.png)

**Comment by rcoenen** [comment]
Answering own issue: you need to drag the ROM file on the actual icon (and not it's bounding box) see below

![image](https://user-images.githubusercontent.com/753704/63645521-ee4b0500-c6cd-11e9-8a20-79b1c3351fa4.png)

**Comment by Alessandro1970** [comment]
Hi Dirk, [version beta 2]

I have a problem to change the roms with drag'n'drop. 
IF I drag a rom when I move a rom icon on the mac it moves well, but as soon as i enter with the icon in the VirtualC64 window to place it in the right place a great slowdown occurs and some roms are no longer recognized, i don't know if it's the last update Apple or beta2, but previously I changed roms quickly and without problems.
...the mouse color loading wheel appears instead the black arrow and the emulation slow down.
Changing the rom after long time the reset is needed to see the changes, otherwise the Rom cannot be seen changed

[VirtualC64_2019-08-03-095427_MacBook-Pro-di-Alessandro.cpu_resource.txt](https://github.com/dirkwhoffmann/virtualc64/files/3537930/VirtualC64_2019-08-03-095427_MacBook-Pro-di-Alessandro.cpu_resource.txt)

**Comment by Alessandro1970** [comment]
I noticed that the slowdown happens even if I do fly over any file, without releasing the left mouse button.
If I try to move any image onto the Rom preference window of VirtualC64, VirtualC64 immediately slows down the Mac as if it wanted to analyze the file that passes over without even the left mouse button being released.
Before it was faster and this problem did not occour.

**Comment by Alessandro1970** [comment]
I made a video about it, if it is needed:

[video virtualc64.mp4.zip](https://github.com/dirkwhoffmann/virtualc64/files/3537950/video.virtualc64.mp4.zip)

**Comment by dirkwhoffmann** [comment]
> I made a video about it

Just watched it. I think it must be related to some refresh callback when drag and drop is active. I guess, I am doing some time-expensive stuff there.

BTW, what web browser is that? 😳

<img width="711" alt="Bildschirmfoto 2019-08-25 um 10 50 35" src="https://user-images.githubusercontent.com/12561945/63647785-a7d5c480-c726-11e9-8292-9a08b784c1e5.png">

It looks like the browser which I used in die Middle Ages when we had to browsed the web via the telephone line and a modem 😅.

**Comment by Alessandro1970** [comment]
That browser is opensource Seamonkey, I use it ...because it has a html editor integrated that I use from the stone age...

**Comment by Alessandro1970** [comment]
The slow down seems to me in all the emulator preferences window...
Do you have any problem in the preferences panel of VirtualC64 ?

**Comment by Alessandro1970** [comment]
Solved:
Removed all about VirtualC64 and a new fresh installation.

There where some configuration files corrupted probably after update...

**Comment by dirkwhoffmann** [comment]
> Removed all about VirtualC64 and a new fresh installation.

😯 Ooohhhh, solved by the Windows way. Apple is becoming the new Microsoft 😢.

**Comment by dirkwhoffmann** [comment]
>  Seamonkey

BTW, we need to try out Monkey Island on vAmiga 🐒. This is where your web browser had beed developed, I guess.

**Comment by Alessandro1970** [comment]
https://www.seamonkey-project.org/

Is out a new version of vAmiga ?

**Comment by dirkwhoffmann** [comment]
> Is out a new version of vAmiga ?

No. I'm still in a fight with the slow Blitter 😖. So we better wait with testing.

**Comment by Alessandro1970** [comment]
Overwrite the beta2 has done it.
Now all is working fine, for me you can close.
