### ISSUE TITLE
Is Virtual 64/VAmiga Catalina Ready?

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#536]
Is Virtual 64/VAmiga Catalina Ready?

**Comment by bryanletcher** [comment]
Yes.  I am running macOS Catalina, release version, and it launches

I do wish they it was from an identified developer so I do not get the following error and have to go to Security & Privacy and allow the application to run.

"VirtualC64.app" can't be opened because Apple cannot check it for malicious software.  This software needs to be updated.  Contact the developer for more information.  Yes, I could

**Comment by dirkwhoffmann** [comment]
I agree the warning message is annoying. Maybe I will register as a developer in future to get access to code signing.

I'm a little hesitant to do so because Apple products are getting worse and worse and I don't want to keep throwing as much money at Apple as I did in the past. In recent years, code quality has been declining steadily, as has usability. Example? Try compiling vAmiga in "Release Build" mode and the Swift Compiler will enter an infinite loop. I don't even want to talk about hardware. I'm one of those unfortunates who spent a huge amount of money to get a butterfly keyboard in return ("It just works"? No, it's broken by design). The first one had dead keys right from the start and the replacement is not very reliable, too. 

The only reason why I stick to Apple at the moment is the lack of alternatives. Windows is still worse in my opinion and Linux still too fragmented (as it always was).

**Comment by Alessandro1970** [comment]
I have tried several times to replace the system with Linux.
I appreciate Linux and could represent the solution to many problems if not all, but I have always had driver problems and hardware incompatibility some years ago, I do not know the situation about today.
... if Commodore could raise again...

But ... if VirtualC64 and vAmiga were released under Linux, for what I use computers at home ... I swear to you all, that I would switch to Linux!

**Comment by PakkunKinoppi** [comment]
**Linux Mint** is great (than Mac Os which comes from BSD)!

Linux Mint is free and OpenGL were not deprecated !

**WOW for VirtualC64 with the virtual Keyboard under LINUX**, that would be a Great Dream ! 
Not Mac Os is not Macintosh and in the future the MBP will be like a iPAD ....the time of Linux is come !

_Is difficult to port VirtualC64 on Linux ?_

**Comment by Alessandro1970** [comment]
...if you switch to linux with VirtualC64  ...I’ll follow you!
Is really good linux Mint ? Never installed before.

**Comment by PakkunKinoppi** [comment]
Linux Mint Cinnamon is great drivers support, free, stable and fast, only VirtualC64 and vAmiga are missing !!!
![thumb_cinnamon](https://user-images.githubusercontent.com/52820759/66467296-86395e00-ea84-11e9-98b8-323fd49f5b9b.png)

https://blog.linuxmint.com/?p=3786

**Comment by sboesebeck** [comment]
I am a huge fan of discussion of which OS is the best... but should that 
be part of this discussion?

Let's go to IRC for that, there we can start some religious war about 
that... 😉

**Comment by Alessandro1970** [comment]
The first problem is not the os or which os, but ...if we can have VirtualC64 on Linux...

**Comment by sboesebeck** [comment]
yes, sure... but the question is " Is Virtual 64/VAmiga Catalina Ready?" 
- not "is there a way to run virtualC64 on linux or better switch to it 
completely"

And to stick to the topic: VirtualC64 works fine here on Catalina, no 
annoying messages/popups or similar. So in my case it is "ready"....

**Comment by PakkunKinoppi** [comment]
Apple is falling down, the Apple MBP are too expensive and there are no future nor Europe nor by that ARM CPU, you know !
_We are all European, we have Linux why seek other ... Ok !_
What also can I say ? ...or I am too ugly and my mind does not work well (probably) or we have our identity !
There are a lot of good laptop that can run Linux which is free !

**Comment by sboesebeck** [comment]
Apple is falling down as long as it exists... nobody forces you to use a 
Mac - but this thread is about VirutalC64 and wether or not apple is 
doomed (again).

Again, if you want to start a discussion - fine, but maybe in another 
thread for another project.

**Comment by Alessandro1970** [comment]
I think that Pakkun (a friend of Paul) was only asking for a VirtualC64 Linux version !

**Comment by dirkwhoffmann** [comment]
I've opened up another thread for the Linux question.

**Comment by bluecursor** [comment]
I own a PC and a mac. My PC collects more dust and hardly sees any action as I use my mac just about every day. I prefer osx over windows any day.

All I know is, VICE for OSX is no longer supported, making there a still a need for a c64/amiga (and even a c128) emulator on macs regardless which way apple goes. So Changing platforms doesn't make sense to me,  but adding other platforms (in the future) does


Thanks for the confirmation that we're catalina ready.


On Oct 9, 2019, 6:43 AM -0400, Dirk Hoffmann <notifications@github.com>, wrote:

I've opened up another thread for the Linux question.

**Comment by bluecursor** [comment]
before upgrading...

https://www.macworld.co.uk/feature/mac-software/apps-wont-work-catalina-3698142/

**Comment by UgoCaneFifone** [comment]
Updating Catalina, I'll report after restarting and playnd some time with VirtualC64!

**Comment by dirkwhoffmann** [comment]
> All I know is, VICE for OSX is no longer supported

Uhh, I haven't heard about that rumor yet. Any reasons for that?

**Comment by bluecursor** [comment]
I have a friend that works on the development of machine. He has told me that they stopped working in the cocoa version over a year ago and now are stopping development on the sld version (mac only). There is no compiled version of vice 3.3 for mac and reasons why.
On Oct 11, 2019, 8:47 AM -0400, Dirk Hoffmann <notifications@github.com>, wrote:

All I know is, VICE for OSX is no longer supported

Uhh, I haven't heard about that rumor yet. Any reasons for that?

**Comment by Alessandro1970** [comment]
I am using VirtualC64 from this morning with catalina but I have not catch problems nor other issues. All is working fine
