### ISSUE TITLE
New Colodore Palette

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#540]
Hi, can be added the new Colodore palette in VirtualC64 ?

Vic - Vic II and TED (P4)

https://www.colodore.com/

![Untitled 2](https://user-images.githubusercontent.com/34916641/68288207-474af800-0084-11ea-9072-df0141735be3.jpg)

**Comment by Alessandro1970** [comment]
Found on this Java emulator:

VPL File:
[colodore.zip](https://github.com/dirkwhoffmann/virtualc64/files/3818128/colodore.zip)


![Untitled 2](https://user-images.githubusercontent.com/34916641/68365317-9484a380-0130-11ea-9988-cdb1a90077eb.jpg)

**Comment by dirkwhoffmann** [comment]
The Colodore palette has been designed by Pepto who did a great job investigating color computation on the VICII. Not only did he dive deeply into the theory, but he also described his findings in a couple of articles that are a pleasure to read: 

http://www.pepto.de/projects/colorvic/
http://unusedino.de/ec64/technical/misc/vic656x/colors/

VirtualC64 is using Pepto's color computation approach since v3.0.

**Comment by Alessandro1970** [comment]
Great article.
I didn’t know that the colodore was the same as Pepto.

**Comment by UgoCaneFifone** [comment]
In VICE there is the possibility to select Pepto, Colodore or Community palette and more, could be a good idea to import all the palette file from there if possible.
To do so I upload here all vice 3.3 palette resource files:
[VICE VPL PALETTE FILES.zip](https://github.com/dirkwhoffmann/virtualc64/files/3932545/VICE.VPL.PALETTE.FILES.zip)

**Comment by dirkwhoffmann** [comment]
I think it's better to keep the color computation stuff as it is. Since v3.0, it's very flexible as brightness, saturation and contrast can be adjusted freely. I guess most predefined color palettes can be approximated adequately by adjusting the three parameters.
