### ISSUE TITLE
Keyboard [CONTROL] Commands dont Work using Turbo Pascal

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#542]
See Help file for commands. Unable to use normally. Have to use Keyboard Window.

[Archive.zip](https://github.com/dirkwhoffmann/virtualc64/files/3821839/Archive.zip)

**Comment by dirkwhoffmann** [comment]
Did you use symbolic or positional key mapping? 

In symbolic key mapping mode, the control key is *not* bound to the C64 CTRL key, because it is a modifier key. In positional key mapping mode, the CTRL key is mapped to the TAB key by default. 

<img width="758" alt="Bildschirmfoto 2020-09-16 um 16 17 59" src="https://user-images.githubusercontent.com/12561945/93350209-ad71e100-f838-11ea-8667-02e6cda272fb.png">

In positional mode, I had no problems with Turbo Pascal.
