### ISSUE TITLE
Add ability to add Function Keys to Customize Toolbar

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#544]
Add ability to add Function Keys to Customize Toolbar? Just showing the one ones i select that i use the most, especially on boot/load of disk ie( jaffydos f1 f2)

**Comment by dirkwhoffmann** [comment]
I thought about it in more detail, but I don't see how this would nicely fit into the current UI design. On the one hand, if I added a separate toolbar item for each function key, there would be a confusing large amount of items to choose from (at least when configuring the toolbar). On the other hand, if I added a dropdown button that lets the user select a function key, there would be no real benefit for the user. 

Accessing function keys might be a more relevant issue for the web ports as it is for the Desktop version, because it should always be quicker to press a function key on the keyboard than hovering over a toolbar icon with the mouse.
