### ISSUE TITLE
Space pressed continuesly with USB Gamepad

### ISSUE THREAD

**Issue by moseisleydk** [dirkwhoffmann/virtualc64#548]
I love Virtual C64 - and have both 2 types of USB game pads.

Whenever the games start, the virtual keyboard flickers and the figura controlled in a game is acting like space is pressed repeatly - typically as autofire.

Im aware that they are not on http://www.dirkwhoffmann.de/virtualc64/ROMs.html

**Comment by dirkwhoffmann** [comment]
Which two USB game pads did you use exactly?

**Comment by moseisleydk** [comment]
https://www.amazon.co.uk/iNNEXT-Controller-Classic-Joystick-Raspberry-Multi-Colored/dp/B01EA7MVTQ/ref=sr_1_1?crid=SWKIPPQUFRCJ&keywords=innext+controller&qid=1580401885&sprefix=innex%2Caps%2C158&sr=8-1

and 

https://www.amazon.co.uk/Classic-Controller-iNNEXT-Joystick-Raspberry-1-Pack-Gray/dp/B075SYB1JX/ref=pd_bxgy_img_2/257-8794898-9906565?_encoding=UTF8&pd_rd_i=B075SYB1JX&pd_rd_r=565ca350-4b4f-423c-b15c-b0d5af99282b&pd_rd_w=HPd6l&pd_rd_wg=sF47N&pf_rd_p=8cf8211e-e7fc-4d94-8247-d0974391e7fd&pf_rd_r=W9VKN0VV246AEMFBVQ8R&psc=1&refRID=W9VKN0VV246AEMFBVQ8R

Also tried a PS4 controller same issue.

**Comment by moseisleydk** [comment]
Im on a Mac, Catalina OS.
Will ship a short video

**Comment by dirkwhoffmann** [comment]
I've just ordered one of the iNNEXT-Joysticks from Amazon. I'll see what I can do...

> Also tried a PS4 controller same issue.

Hmm, the PS4 controller should work. Does the emulator recognise the PS4 controller by name?

**Comment by moseisleydk** [comment]
OK, cant make Quickfind working to take screen movies :--(
Will look into it

**Comment by dirkwhoffmann** [comment]
I tried both gampads today. I started with the bigger one. This one had an issue with the hatswitch:

<img width="367" alt="Bildschirmfoto 2020-02-02 um 16 31 53" src="https://user-images.githubusercontent.com/12561945/73610841-0196c080-45dc-11ea-968c-147f7d2a5322.png">

The reason was quite simple. When releasing a button, the device sends a value of 15 whereas all other gamepads I have send 8. I’ve fixed this by modifying GamePad.swift as follows:

Old: 

```
        case kHIDUsage_GD_Hatswitch:
                
                switch intValue {
                case 0: events = [PULL_UP, RELEASE_X]
                case 1: events = [PULL_UP, PULL_RIGHT]
                case 2: events = [PULL_RIGHT, RELEASE_Y]
                case 3: events = [PULL_RIGHT, PULL_DOWN]
                case 4: events = [PULL_DOWN, RELEASE_X]
                case 5: events = [PULL_DOWN, PULL_LEFT]
                case 6: events = [PULL_LEFT, RELEASE_Y]
                case 7: events = [PULL_LEFT, PULL_UP]
                case 8: events = [RELEASE_XY]
	        default: break
                }

```
New:

  ```
      case kHIDUsage_GD_Hatswitch:
                
                switch intValue {
                case 0: events = [PULL_UP, RELEASE_X]
                case 1: events = [PULL_UP, PULL_RIGHT]
                case 2: events = [PULL_RIGHT, RELEASE_Y]
                case 3: events = [PULL_RIGHT, PULL_DOWN]
                case 4: events = [PULL_DOWN, RELEASE_X]
                case 5: events = [PULL_DOWN, PULL_LEFT]
                case 6: events = [PULL_LEFT, RELEASE_Y]
                case 7: events = [PULL_LEFT, PULL_UP]
                default: events = [RELEASE_XY]
                }

```

The analog stick seems to work though. 

I had no issue with the small controller at all (the one with the hatswitch only). 

Interestingly, both devices register with a completely different vendor ID (0xF0D for the big one and 0x79 for the little one). I guess the hardware is completely different and they just labeled „iNNEXT“ on both of them, whoever that company is. Also interesting: The hatswitch of the little one pretends to be an analog stick and not a hatswitch. 

For testing the modified implementation, I took some flight lessons today (note: the game controller is now recognised by name 😎):

<img width="639" alt="Bildschirmfoto 2020-02-02 um 16 50 28" src="https://user-images.githubusercontent.com/12561945/73610860-2d19ab00-45dc-11ea-9e1e-eb0409c79254.png">

It seems to work, but you won’t have much fun with these controllers (you'll crash one helicopter after another). The controllers are sold for little money, but they are worth even less. The best choice at the moment might still be the Competition Pro (USB) or a real Competition Pro plugged in with a USB retro adapter. If somebody knows another decent joystick, please let me know. I’ve also tried the joystick of the C64 Maxi, but it’s not as good as I thought (although the new version has micro-switches). 

If you don’t want to wait for the next VirtualC64 release, you can always download the code from the main branch and compile it in Xcode. It should compile out of the box (with Xcode 11.3 which is the latest version). The fix is already checked in.

**Comment by moseisleydk** [comment]
Awesome, I will wait for the new version.
Need to find some great and free screen recorder for Catalina. Quickmovi is wierd... :-)

**Comment by LSDdev** [comment]
> Need to find some great and free screen recorder for Catalina. Quickmovi is wierd... :-)

Quicktime's own screen recording is quite handy :)
