### ISSUE TITLE
Waiting for 3.4 final release...

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/virtualc64#551]
Waiting for the fina 3.4 release ...like VICE tha is on its 3.4 (better to skip and go to VirtualC64 release 3.5)...
I would ask for an implementation about colour scheme: like in VICE could you add in the pre-set scheme  (amber, green, etc) the colordore, pepto pal, community colours  and other colour schemes that can be found on VICE ?

**Comment by PakkunKinoppi** [comment]
This is a good idea, preset colour scheme are good (Communiti edition is fine)

**Comment by Alessandro1970** [comment]
Is this one ?

![Untitled 2](https://user-images.githubusercontent.com/34916641/75249891-702ffe00-57d7-11ea-9d05-e0f59a9285d3.png)

**Comment by Alessandro1970** [comment]
I do not use **VICE_Hugly** but I looked those schemes time ago: Pepto PAL is good for me and some games are good with Community but the others...
Colodore is near VirtualC64 if I remember, time ago there was an issue about it

**Comment by Alessandro1970** [comment]
Are we near a 3.5 release ?
...far away ViceSC_VirusT (Umbrella corporation ndr... hem  :zipper_mouth_face:

**Comment by dirkwhoffmann** [comment]
> This is a good idea, preset colour scheme are good

I had color schemes in the older versions of VirtualC64, but kicked them out when I switched over to the Colodore approach. Since v3.0 the color palette is synthesised out of three parameters: brightness, color, and saturation. Hence, there is noch such thing as a fixed Colodore palette. Colodore should be seen as a  method for synthesising color palettes. 

> Are we near a 3.5 release ?

My longer term goal is to bring vAmiga and VirtualC64 close together. Compared to VirtualC64, vAmiga has a superior software-architecture and I want to merge the improvements back into VirtualC64 at some point. Of course this only makes sense once vAmiga has stabilised which will take some more time. VirtualC64 has a lower priority for me at the moment, because it just wouldn't make sense to stop the vAmiga project at this point in time. vAmiga has evolved very well. A year ago, I hadn't though in my dreams that I eventually come so far.

**Comment by rossimariolee** [comment]
...switching to 3.5 final new release next week skipping the 3.4 ?
:rofl: 
...we are waiting for !  
...and any news for Apple risk cpu for macbook ? VirtualC64 will be ported to ?

**Comment by Alessandro1970** [comment]
What a pity, right now that I wanted to buy a new macbook. Needless to buy an MBP and then watch the CPU change.
... it would be a MBP to be thrown away, just like with PowerPC.
When to switch to RISC?

**Comment by dirkwhoffmann** [comment]
v3.4 has been releases today.
