### ISSUE TITLE
Moonspire not working

### ISSUE THREAD

**Issue by Shrapnel21** [dirkwhoffmann/virtualc64#568]
Quick and simple: Moonspire by RGCD just hangs the emulator on start.
I don't know if it's a GMOD2 cartridge, though, in which case it would be 'normal' for it to fail, right?

**Comment by dirkwhoffmann** [comment]
I don't have the Moonspire CRT. It's from 2018 and therefore doesn't qualify as abandonware 🙁.

**Comment by Shrapnel21** [comment]
Yep, you're right! I didn't pirate it, of course =) , but got it as a bonus when I bought the game on cart. =D

**Comment by sarnau** [comment]
Is this the game? [https://rgcddev.itch.io/moonspire](url)

**Comment by Shrapnel21** [comment]
> Is this the game? [https://rgcddev.itch.io/moonspire](url)

Yep, that's the one. =)

**Comment by dirkwhoffmann** [comment]
This turned out to be an easy one. The CRT file asks to be started in Ultimax mode. However, the cartridge is of type "Magic Desk" and cartridges of this type always run in 8K game mode. If the initial Game/Exrom setting from the CRT is ignored, the game works like a charm: 

<img width="922" alt="Bildschirmfoto 2021-01-03 um 14 23 20" src="https://user-images.githubusercontent.com/12561945/103479719-e4600880-4dcf-11eb-933d-40f632100b0b.png">

**Comment by Shrapnel21** [comment]
Awesome, one more game becomes playable on the emulator! =)
I'm afraid GMOD2 isn't gonna be that easy though, right? =(

**Comment by dirkwhoffmann** [comment]
> I'm afraid GMOD2 isn't gonna be that easy though, right? =(

GMOD2 is explained here:
http://wiki.icomp.de/wiki/GMod2

This all sounds very familiar. It may well be that the original Moonspire cartridge is based on the GMOD2 hardware. The "Magic Desk" identifier is part of the CRT file. It does not exist in real hardware and simply tells emulators how to deal with the cartridge.

**Comment by Shrapnel21** [comment]
Yep, Moonspire was actually thought to be a GMOD2 cart when it came out, but it apparently lacks the flash memory for saves from GMOD2. Real GMOD2 games are made out of two files when digitally distributed for emulators, one of those should be the flash portion.
