### ISSUE TITLE
Emulator crashes when loading Archon from tape

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#579]
The crash occurred in the web version, but the desktop version is almost certainly affected, too. 

![90681121-2f371480-e263-11ea-8194-31da0946e879](https://user-images.githubusercontent.com/12561945/90687226-d53b4c80-e26c-11ea-9ac3-c99c305d9981.png)

**Comment by mithrendal** [comment]
no close it .. the same tap files works with vc64mac 

<img width="996" alt="image" src="https://user-images.githubusercontent.com/17108995/90689495-7677d200-e270-11ea-845d-3284f8116c45.png">

and with vc64web too



in vc64web I just dragged the tap file into the file slot and then typed load  

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/17108995/90689795-eab27580-e270-11ea-861e-fdd28010d6dc.png">


when doing it correctly just with the "load" command then all is fine...

the crash was due to the fact that I loaded it wrong with  load"archon",1,1  whereas the the file had the name "adept" so it loaded forever until it run into the assertion...

**Comment by mithrendal** [comment]
oh no I was wrong ... first it loaded normally like vc64mac ... but in the end vc64web still got this on adept2 tape ...

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/17108995/90690947-d2435a80-e272-11ea-96d8-fafb87e29eb9.png">

**Comment by dirkwhoffmann** [comment]
Fixed in the v3.4 branch (in case we should need a 3.4.1) and the dev branch (v4.0).

**Comment by mithrendal** [comment]
loading locally with new datasette

![grafik](https://user-images.githubusercontent.com/17108995/90763145-79ada500-e2e6-11ea-984a-c6b6da7d710b.png)



and... 

![grafik](https://user-images.githubusercontent.com/17108995/90763168-803c1c80-e2e6-11ea-9b43-e5f25a3375a2.png)



success !!! The fix did it too for the vc64web edition ...

**Comment by mithrendal** [comment]
pushed new version to gh-pages
