### ISSUE TITLE
Is there any way to rewind tapes to a certain position?

### ISSUE THREAD

**Issue by kerunaru** [dirkwhoffmann/virtualc64#587]
Hi!

I'm just trying to play to X-Out. This game ask the player to rewind to a certain position (a number in the counter on the datasette) in order to load the shop between the stages or the title screen if you lost all your lives.

I found easy to do that on VICE, but it seems it's impossible to achieve this in VirtualC64… Maybe I'm just to clumsy and I can't find the way or maybe this could become into a feature request for the next 4.0 version 😉

Thanks for this awesome emulator! Keep the good work!!

**Comment by dirkwhoffmann** [comment]
You are right, rewinding a tape is not possible in VirtualC64 (yet). Actually, I never thought somebody would use the Datasette at all. Technically, rewinding is easy, because the Datasette class already has the necessary code on board (which is to convert minutes and seconds to impulse offsets). The more difficult thing is to integrate this functionality nicely into the GUI.

**Comment by mithrendal** [comment]
>The more difficult thing is to integrate this functionality nicely into the GUI.

🥴action buttons for all those non common functions ?

**Comment by dirkwhoffmann** [comment]
In the next version it'll be possible to rewind (or fast forward) the tape to a specific position (via the debug console):

<img width="917" alt="Bildschirmfoto 2021-05-01 um 14 49 53" src="https://user-images.githubusercontent.com/12561945/116783439-0e2ff000-aa8f-11eb-825d-36c832c5e31a.png">

There is a caveat though: The argument is specified in seconds which is not identical with what the datasette counter displays. The counter of a real datasette counts revolutions with is not proportional to the elapsed time. It depends on the position of the tape and even the thickness of the magnetic tape.
