### ISSUE TITLE
Basic program out of data, but works fine in Vice

### ISSUE THREAD

**Issue by bnice** [dirkwhoffmann/virtualc64#594]
Hi,

Basic program "ROX 64" out of data, but works fine in Vice. This is weird one. I went back and checked my rom versions and Basic, Characters, and Kernel V3.

[Rox 64.T64.zip](https://github.com/dirkwhoffmann/virtualc64/files/5633484/Rox.64.T64.zip)

Regards Ben.

**Comment by dirkwhoffmann** [comment]
So far, it works well here: 

<img width="990" alt="Bildschirmfoto 2020-12-13 um 16 28 46" src="https://user-images.githubusercontent.com/12561945/102016301-7d1adf80-3d60-11eb-87d4-ec04248ca34e.png">

I did the following:

- Dragged in T64 file
- Chose "Insert as disk"
- Typed `LOAD "*",8`
- Typed `RUN`

**Comment by dirkwhoffmann** [comment]
I'm not smart enough for this game. How do I shoot the asteroids? When I hit space, my "panic" weapon fires and the asteroid is gone. But I only have three "panics" available. 🤔

Oh no, this one is close 😬

<img width="988" alt="Bildschirmfoto 2020-12-13 um 17 55 23" src="https://user-images.githubusercontent.com/12561945/102018289-b5c0b600-3d6c-11eb-9bf4-4fce0d32263e.png">

I knew it 🙈

<img width="988" alt="Bildschirmfoto 2020-12-13 um 17 55 27" src="https://user-images.githubusercontent.com/12561945/102018298-c53fff00-3d6c-11eb-9d68-98dbb9cee52a.png">

**Comment by dirkwhoffmann** [comment]
Found it. You've most likely flashed the program into memory which results in this:

<img width="988" alt="Bildschirmfoto 2020-12-13 um 19 14 38" src="https://user-images.githubusercontent.com/12561945/102020486-d04d5c00-3d79-11eb-92fc-bdaa33d99104.png">

I've checked that the load address in the T64 file is fine (equals $801). I guess the reason is that flashing the program doesn't trigger any of the side effects that get triggered when the program is loaded regularly via `LOAD "*",8`. I'm unsure what VICE is doing. Since flashing works fine in VirtualC64 for most (non Basic) programs, I think it's not worth looking into the VICE source code (if anybody wants to do it, please go ahead).

Last, but not least: I've figured out how to shoot missiles 😎 (no, I won't tell):

<img width="988" alt="Bildschirmfoto 2020-12-13 um 19 14 15" src="https://user-images.githubusercontent.com/12561945/102020574-4e116780-3d7a-11eb-88f4-f40b89c570af.png">

**Comment by bnice** [comment]
Hi,
What I actually used to load it was File menu Open... I see now on the second dialog it brings up, says double clicking the item flashes the item into memory. I guess I am old fashion using the File menu and Open it use to be only way to open files in the early Amiga and Mac days 🙂 and was the only way I could get it load T64 didn't think of drag and drop.

Ben.
