### ISSUE TITLE
new ReSID driver broken ... on complex music 

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#603]
the problem arises in complex music

testcase:  https://markus-klein-artwork.de/sid/vortex.html
(it also has a youtube clip with an original 8580 Chip, and a sid file which plays well in SID Player http://www.sidmusic.org/sidplay/mac/)

Version 3.4 of virtualc64 also plays Vortex very well even ReSID engine with nearest neighbbours sampling ... the FASTSID engine could not cope with that type of complex SID music ...

current master (Version 4.0)  can not play Vortex with ReSID nearest neighbbours  anymore, also Interpolate and Resample has strange background noise (like buzzing ....)  ...

I forked the repo and created a branch preMultiSID where ReSID in Version4 still works clean (29.11.2020) ...
https://github.com/mithrendal/virtualc64/tree/preMultiSID

some new changes after 29.11.2020 made a great difference on how ReSID performs on that type of music ...

**Comment by dirkwhoffmann** [comment]
The good: I think I know what it is.
The bad: It’s a major design flaw in the new multi-SID pipeline.

Background: The old implementation run reSID in small delta steps which were measured in cycles. This caused reSID to produce a varying number of samples in each call. This is perfectly fine for single-SID emulation, but makes multi-SID emulation more difficult. To ease multi-SID emulation, I tell every SID to produce a certain number of samples instead of advancing a certain number of cycles. However, I didn’t take into consideration that this works perfectly fine only when SID doesn’t interact with the „outer world“. Of course, there is some interaction in form of SID register writes that occur at certain cycles. With the old approach I was able to run SID up to the correct cycle before changing the register contents. With the new approach I am only able to run SID up to the correct „sample“. In other words: Timing accuracy of the SID pipeline has degraded from cycle accuracy to sample accuracy.  

What I need to do is to rework the current design. Each SID needs to get a separate ring buffer which enables it to produce sound samples independently of the other SIDs. In the second stage, the samples of these buffers get mixed together and copied into the already existing ring buffers for the left and right output channel. The proposed emulation code will be slightly more time consuming, because new ring buffers come into play, but I don’t expect a severe performance cut.

**Comment by mithrendal** [comment]
>The proposed emulation code will be slightly more time consuming, because new ring buffers come into play, but I don’t expect a severe performance cut.

could you designed it in a way, that when only one SID is configured, that it will directly write into the second stage ringbuffer (e.g. omitting SID1.ringbuffer copy to global.ringbuffer) ? That way performance hit with only one configured SID would be optimized to an minimum ... thinking of climate warmth and that the majority programms out there are single SID only ...

**Comment by mithrendal** [comment]
loaded vortex ... started it ... and before any sound comes out of the speakers .. this assertion compains ...
![grafik](https://user-images.githubusercontent.com/17108995/103167639-2667d800-482d-11eb-9af7-c62b17d9d42d.png)

**Comment by dirkwhoffmann** [comment]
That's the new "ear protection feature": 

 ```
        // Apply ear protection
        assert(abs(l) < 0.15);
        assert(abs(r) < 0.15);
        
        stream.write(SamplePair { l, r } );
```

Can you check the sample values? Maybe the web version required different scaling factors?

**Comment by mithrendal** [comment]
samples from vortex coming in ...

producer code 
```

        // Apply ear protection
        if(abs(l)>maxl || abs(r)>maxr)
        { 
            if(l>maxl)
              maxl= abs(l); 
            if(r>maxr)
              maxr= abs(r); 
              
            
            printf("l=%f, r=%f\n", maxl, maxr);
        }
        
    //    assert(abs(l) < 0.15);
    //    assert(abs(r) < 0.15);

```

produces this

![grafik](https://user-images.githubusercontent.com/17108995/103168195-6a5cdc00-4831-11eb-87a5-de5ebad89cc8.png)


why is it so unbalanced ... did I misconfigured it ? I mix it to mono in the web version anyway so it doesn't matter right ?

**Comment by dirkwhoffmann** [comment]
> why is it so unbalanced 

I guess you didn't initialise the pan values:

<img width="637" alt="Screenshot 2020-12-27 at 11 59 39" src="https://user-images.githubusercontent.com/12561945/103169462-291df980-483c-11eb-85e4-6840d88b8d36.png">

I've checked in new code on the dev branch that initialises these values with 0 (which is what you want for mono). The channel volumes are also initialised by 0. Make sure to set them to suitable values in your init code.

**Comment by mithrendal** [comment]
I have found the Pan problem ... it was configured ... but with a misinterpretation of the values on my side ....

I configured it like this ...
```
  //SID0 Volumne
    c64->configure(OPT_AUDVOL, 0, 100); 
    c64->configure(OPT_AUDPAN, 0, 50);
```

now I corrected it so ...
```
  //SID0 Volumne
    c64->configure(OPT_AUDVOL, 0, 100); 
    c64->configure(OPT_AUDPAN, 0, 0);
```

and this results in these balanced abs max values 
![grafik](https://user-images.githubusercontent.com/17108995/103172245-6ab99f00-4852-11eb-8be5-359efea88e25.png)


still it would hang at the assertion ... do I have to lower the volumne ? Maybe it is wiser to let the HOST OS do the ear protection instead ?

**Comment by dirkwhoffmann** [comment]
> still it would hang at the assertion ... do I have to lower the volumne ?

No, just increase the assertion value. I only wanted to protect against what happened last week (when I forgot to multiply the final sample with 0.000025 😬).
