### ISSUE TITLE
4.0b1 - Flash Top Bar Filename Identifier

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#611]
If you flash a file over an existing game loaded, it doesn't change the top bar program name. Pic shows I originally loaded Wacky Darts prg but flashed in Wavy Navy prg and filename on the top bar was not updated

![Screen Shot 2021-01-14 at 8 19 01 AM](https://user-images.githubusercontent.com/31462938/104596298-cef5a480-5641-11eb-8a32-9fd0e489fab3.png)

**Comment by dirkwhoffmann** [comment]
The correct behaviour is to show "Untitled" in this case, because there is no snapshot file associated with the emulator instance.

**Comment by dirkwhoffmann** [comment]
Having thought this through thoroughly, I plan to solve this problem with a measure that I know will be unpopular. 

First, some background information: VirtualC64 has the "editor" role for VC64 files (snapshots), which means that files of this type can be read or saved. This allows the emulator to be started by double-clicking on a snapshot file or by dragging a snapshot file onto the app icon.

In the past, several users have requested to have the same functionality for D64 files, T64, etc. These files should be able to be dragged onto the app icon and the emulator should start. To make this possible VirtualC64 had to have at least the "viewer" status for these files. 

Unfortunately the declaration of VirtualC64 as "viewer" for these files is semantically inconsistent. Why? Because D64 is never the document type. The document type is VC64. Always. 

Internally, I had to use some tricks to get around this semantic inconsistency. For example, I invented something like a "media attachment" that can be assigned to a document. When a D64 is dragged onto the app icon, it is first converted to a media attachment because the document classes are not yet initialized enough to do anything with the D64 file. At a later time, the attachment is picked up and the D64 file is processed. From a software aesthetic point of view, this is all ugly. 

So I'm going to make a clean cut here and eliminate the semantic inconsistency. The next version will loose the "viewer" status for D64, T64 files etc. Of course, these files can still be used. They can be added by drag and drop, and they can be inserted into drives by selecting the appropriate menu item. But it is no longer possible to double-click on these files or drag them onto the app icon. MacOS will no longer associate these files with VirtualC64. 

On the positive side, I will be able to clean up the internal code base in several places. First and foremost, I will be able to get rid of all the media attachment stuff that I never really liked.

**Comment by bluecursor** [comment]
Loosing the ability to double click on a .prg or .d64 is a big issue.  I rely on it and I am sure others do too.

Frank Michielli
Sent with OSX/iOS Spark!

**Comment by dirkwhoffmann** [comment]
Should be fixed in v4.0b2.

Double clicking on v4.0b2 still works since I've subclassed NSDocumentController. If the emulator is started with a media file on board, the document controller saves the media file and redirects the call to the code that is called  when a new (untitled) document is created.
