### ISSUE TITLE
4.0b3 - Disconnect emulation keys

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#622]
Arrow up key still locked when deselecting disconnect emulation keys.

**Comment by dirkwhoffmann** [comment]
It's not a bug. When the arrow keys are selected as emulation keys for devices in port 1, the cursor keys won't work. This is because the keyboard matrix and control port 1 use the same CIA register. As a result, the C64 can't fully distinguish key presses from joystick movements. To better see what I mean, plug in a joystick in port 1. Moving the joystick will produce weird characters on the screen, because the C64 recognises these movements as key presses.
