### ISSUE TITLE
4.0b4 Tabs

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#627]
Can not no longer create a 2nd tab when dragging. in a .d64 or flash onto the first instance of the emulator. It just duplicates but doesn't create the new tab.

**Comment by dirkwhoffmann** [comment]
I am not sure if I understand correctly what you did.

When I open the app and drag a D64 file into the canvas, it looks like this (which is correct): 

<img width="922" alt="Bildschirmfoto 2021-01-23 um 06 59 41" src="https://user-images.githubusercontent.com/12561945/105570300-c63f5580-5d48-11eb-9c93-baaac1ee6470.png">

When I open the app and drag a D64 onto the app icon, it looks like this (which is also correct): 

<img width="885" alt="Bildschirmfoto 2021-01-23 um 06 59 09" src="https://user-images.githubusercontent.com/12561945/105570315-dce5ac80-5d48-11eb-9b59-568d80349486.png">

What do you mean by "it just duplicates"?

**Comment by bluecursor** [comment]
Here is a screen capture: https://workupload.com/file/uvZtMVTp5M8

**Comment by dirkwhoffmann** [comment]
Thanks a lot for the video!

> if you drag it a .d64 into a running emulation, it would create a new tab?

No, it's not supposed to open a new tab. If you drag in a media file and hit "Drive 8" the disk is supposed to be inserted into the drive of the current emulator instance (otherwise, no disk change would be possible via drag and drop). New emulator instances open only if a media file is double clicked or dragged onto the app icon.

**Comment by bluecursor** [comment]
My Error...
