### ISSUE TITLE
Can't map the same Mac key to differents C64 keys

### ISSUE THREAD

**Issue by kerunaru** [dirkwhoffmann/virtualc64#640]
If you map the `.` key and later you try to map the `:`, Virtual C64 assign the previous `.` instead of `:` in the Mac keyboard.
This happens too with `2` and `@`, `+` and `*`, `0` and `=`, `7` and `/`, etc.

Mapping characters instead of keys should fix this.

**Comment by dirkwhoffmann** [comment]
I'm sorry, but I don't understand the issue. I assume you're talking about the positional key map, right?

<img width="566" alt="Bildschirmfoto 2021-02-13 um 14 45 22" src="https://user-images.githubusercontent.com/12561945/107851430-1e2e2100-6e0a-11eb-866c-2b72ea580301.png">

In this mapping mode, every Mac key is either unbound or bound to exactly one C64 key. It wouldn't make sense to bind it to multiple 64 keys, because the positional key map doesn't evaluate key modifiers (such as Shift etc.). If you decide to use the positional key map, a Mac key (if it is assigned) is literally a key on the C64 keyboard. "Mapping characters" is what symbolic mapping does. It analyses the character that is associated with a certain Mac key and translates it to a C64 key combination as best as it can. This key combination can contain, e.g., the Shift key, if the character is only available on the C64 keyboard via Shift.

**Comment by kerunaru** [comment]
I see… I ended up trying to map all the keys because I couldn't find out what Mac key is the C= key in the positional key mapping, that makes use SID Wizard a nightmare because it has some shortcuts using the C= key 🤷‍♂️
