### ISSUE TITLE
V4.0.1 Soft Reset

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#657]
I am unable to get this to work as the PRG requires a soft reset
http://cloud.cbm8bit.com/brataccas/sshelp64.zip

Instructions are:

> Load the .prg file in Vice and perform a soft reset to activate the utility. After reboot, you'll see:
*** STACK SUPER HELP64 ***

**Comment by bluecursor** [comment]
works with SYS 64738 to activate. Can we add a soft reset option?

**Comment by dirkwhoffmann** [comment]
If I understand correctly, you'd like to have an option that types in SYS 64738 automatically (resp. an option that jumps directly to this address). 

I'm unsure if we should add such an option, because it further increases the complexity of the emulator (GUI wise) and there don't seem to be many titles which make use of  a "soft reset".

**Comment by mithrendal** [comment]
>Can we add a soft reset option?

@bluecursor The feature is already there. You can simply add/customize the "soft reset" feature by yourself with a few clicks ... 😊 ... albeit in the web version ...

the web version, due to its nature that it bridges the world of open web with the world of C++ where the virtual c64 emulation core lives in ... takes another approach in terms of scripting and extension ...

![grafik](https://user-images.githubusercontent.com/17108995/112723326-218af100-8f0e-11eb-9689-fe9c020d3eb0.png)


this customization will be persistant, which means on next start the button will still be there...

**Comment by mithrendal** [comment]
lets place a softreset button to the lower left corner with this preconfig link 

https://dirkwhoffmann.github.io/virtualc64web/#{"buttons":[{"position":"bottom:0vh;left:0vw","title":"soft_reset","lang":"actionscript","script":"'sys64738'=>Enter"}]}

@bluecursor clicking this link opens a vc64 with a soft reset button in the lower left corner, is that ok for you ?

**Comment by bluecursor** [comment]
Are we talking for virtual64 or virtual64web? Or is this for both?

Frank Michielli
Sent with OSX/iOS Spark!

**Comment by mithrendal** [comment]
We do currently support customizable/programmable action buttons for the web UI only.

**Comment by bluecursor** [comment]
As I don’t use the web version, my original request was for virtual64.

Frank Michielli
Sent with OSX/iOS Spark!

**Comment by dirkwhoffmann** [comment]
The next version will have a "Soft Reset" item in the Keyboard menu. It'll type "SYS 64738" on the keyboard.

<img width="206" alt="Bildschirmfoto 2021-03-28 um 08 18 20" src="https://user-images.githubusercontent.com/12561945/112744216-4d55b780-8f9e-11eb-8479-e325c9206f55.png">

**Comment by bluecursor** [comment]
Awesome!

Frank Michielli
Sent with OSX/iOS Spark!

**Comment by dirkwhoffmann** [comment]
v4.1 is now online.
