### ISSUE TITLE
Dolphin DOS rom

### ISSUE THREAD

**Issue by PakkunKinoppi** [dirkwhoffmann/virtualc64#684]
Hello, how can I load this rom (Dolphin DOS) which is a quick accelerator for Drive to work?

[DolphinDOS_2.0.zip](https://github.com/dirkwhoffmann/virtualc64/files/6530819/DolphinDOS_2.0.zip)

https://rr.pokefinder.org/wiki/Dolphin_DOS_Manual_Project64.txt

**Comment by dirkwhoffmann** [comment]
This Rom is not supported (yet). DolphinDOS extends the Drive RAM and requires a special cable which has to be connected to the user port.

**Comment by mithrendal** [comment]
I friend of mine had this back then ... it was so fast ... unbelievable fast ... I bet it was faster than todays SSDs ... no ? ok ... but at least it felt the same speed .... back then ... 🤓

**Comment by Alessandro1970** [comment]
Oh yes  …but there is something faster:
https://vintageisthenewold.com/jiffydos-mod-for-dolphin-dos-kernal/

**Comment by Alessandro1970** [comment]
There ia a dolphin dos remake in 2013

https://csdb.dk/release/?id=120055

**Comment by dirkwhoffmann** [comment]
The next release will offer support for Dolphin DOS 2:

<img width="641" alt="Bildschirmfoto 2021-07-25 um 15 10 13" src="https://user-images.githubusercontent.com/12561945/126900672-82516e34-c598-460d-bee7-b84130d0ab56.png">

Here is a brief comparison of different speeders (test case is loading the Goonies game, 167 Blocks):

- Original drive: 1:44 min
- SpeedDOS+: 26 sec
- Action Replay 7.5: 8 sec
- Dolphin DOS 2: 5 sec

Based on these numbers, the silver medal goes to AR 7.5. This is astonishing, because AR 7.5 is a simple cartridge that does not require any hardware modification. It loads faster via the standard serial interface than SpeedDOS+ via the parallel cable.

**Comment by Alessandro1970** [comment]
Yes, you are right.
But with VirtualC64 I think that I will choose the Dolphin because it is cool and the cartridge slot is free.
Thank you, this is really a great update for me.
Bye

**Comment by dirkwhoffmann** [comment]
Available in v4.3 which is now online.

Please reopen if there are any issues with the new cable.

**Comment by dirkwhoffmann** [comment]
A problem with the old implementation was that the user had to configure multiple drive parameters manually to make custom ROMs work. E.g., Dolphin DOS 3 expects expansion RAM at $6000 whereas the Dolphin DOS 1 and Dolphin DOS 2 expect expansion RAM at $8000. 

To cope with this inconvenience, I've implemented a new auto-config option for drives:

<img width="639" alt="Bildschirmfoto 2021-07-29 um 15 07 51" src="https://user-images.githubusercontent.com/12561945/127498691-d743bc58-0d82-4549-8fc1-86bd5d806c2d.png">

When this option is enabled, the drive settings are updated automatically when a known ROM is installed. E.g., when dragging in the Dolphin DOS 3 ROM, the configuration automatically changes to:

<img width="639" alt="Bildschirmfoto 2021-07-29 um 15 08 49" src="https://user-images.githubusercontent.com/12561945/127498708-5a2720f6-adae-4004-92b7-f7d67d38bd09.png">

With the new option, it's much simpler to use HW-based drive accelerators as it is no longer necessary to remember any hardware details. 

BTW, Dolphin DOS 3 will work in the next release, too.

**Comment by Alessandro1970** [comment]
Great !
It will be really simple !
