### ISSUE TITLE
Graphics / Timing Bug?

### ISSUE THREAD

**Issue by MeAndMyRhythmbox** [dirkwhoffmann/virtualc64#687]
This lovely image from the Gubbdata 2021 compo is not displayed correctly - has flashing white background. Wonder if it's just me or perhaps this is a useful test case? 

Changing VIC chip version in hardware preferences produces additional glitches in left and right borders for some settings.

https://csdb.dk/release/?id=205521

![Killing Spree](https://csdb.dk/gfx/releases/205000/205521.png)

**Comment by mithrendal** [comment]
... the web version of virtualC64 seems to be working correct ?

https://vc64web.github.io/#http://csdb.dk/getinternalfile.php/214986/Killing%20Spree%20-TheSarge.prg

@MeAndMyRhythmbox I do not see any flashing in the white background here ... maybe it is related to the metal rendering of your specific mac machine ? Please try the webversion link above to check this ... the webversion uses webgl instead of directly the metal API ...

**Comment by MeAndMyRhythmbox** [comment]
Sorry, my bad - was still running v4.01
Downloaded 4.2 and now everything works great!!!
