### ISSUE TITLE
Int Soccer (Remember Crack) white noise channel turned on when it shouldn't be

### ISSUE THREAD

**Issue by bnice** [dirkwhoffmann/virtualc64#690]
Hi,

Hope you are well, it has been a while. In Int Soccer (Remember Crack) URL below where you can grab it. If you go past the title pic to the white screen with "Commodore" on it, and wait for the player green screen to come up the white noise channel will start and cannot be stopped.

 Loading the Same image in Vice (I use 3.2 as it is the last cocoa version) the white noise channel doesn't start. 

http://archive.org/download/Commodore_C64_TOSEC_2012_04_23/Commodore_C64_TOSEC_2012_04_23.zip/Commodore%20C64%20%5BTOSEC%20v2012-04-23%5D%2FGames%2FCommodore%20C64%20-%20Games%20-%20%5BT64%5D%20%28TOSEC-v2012-04-14_CM%29%2FInternational%20Soccer%20%281983%29%28Commodore%29%5Bcr%20REM%5D.zip

**Comment by dirkwhoffmann** [comment]
This is one of the very first games I played on the C64. OK, graphics isn't really as good as the current version of FIFA, but it's still cool, somehow 😆. 

<img width="979" alt="Bildschirmfoto 2021-08-05 um 16 57 27" src="https://user-images.githubusercontent.com/12561945/128373364-5da3de13-d5ca-4734-9193-9aa39abac65e.png">

With "white noise channel" you are referring to audio output, right? If yes, could you try to disable the following power-saving option?

<img width="640" alt="Bildschirmfoto 2021-08-05 um 17 01 45" src="https://user-images.githubusercontent.com/12561945/128373162-8c2be04a-1904-44ee-967d-ee8df24d6d8d.png">

**Comment by bnice** [comment]
Hi,
Yes, the audio channel that sounds like static noise used for the crowd cheer. This cartridge was the first computer game we brought when we got a C64 in February 1984.

**Comment by bnice** [comment]
Tried unchecking the option suggested, still the same.

**Comment by mithrendal** [comment]
@bnice
You could try the web version to rule out platform related code of the mac version. 

https ://vc64web.github.io/

If the issue occurs there too then it is likely emulation related.

**Comment by bnice** [comment]
Hi, keen to help diagnose. I tried the web emulator, but I am not sure what the run/stop key need to get out of the intro?

**Comment by mithrendal** [comment]
for finding the runstop key you can open the virtual keyboard with the navbar icon 'Aa' ... there you will find all c64 keys

 

 

 
 

Gesendet: Sonntag, 08. August 2021 um 14:00 Uhr
Von: "bnice" ***@***.***>
An: "dirkwhoffmann/virtualc64" ***@***.***>
Cc: "mithrendal" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [dirkwhoffmann/virtualc64] Int Soccer (Remember Crack) white noise channel turned on when it shouldn't be (#690)


 

Hi, keen to help diagnose. I tried the web emulator, but I am not sure what the run/stop key need to get out of the intro?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bnice** [comment]
Hi,
So got to trying the web version again and didn't have the same fault. I look back at the audio settings page and see there is an audio filter option checking this suppressed the static noise.

**Comment by dirkwhoffmann** [comment]
> there is an audio filter option checking this suppressed the static noise

Excellent. This explains why I had trouble reproducing the problem (filter is enabled in my settings).
