### ISSUE TITLE
Disk insert feature missing and program mod causing a crash

### ISSUE THREAD

**Issue by SJCunninghamHall** [dirkwhoffmann/virtualc64#727]
Hi,

I have downloaded the latest version of VirtualC64 and cannot see how to "insert" a D64 file. For example, I cannot see a "Load disk" item in any of the menus.

I understand that a D64 image can be dragged into the emulator. However the reason I need to virtually insert a disk rather than drag and drop the D64 file is that in order to play a particular game (The Fourth Protocol), the file "GAME" needs be loaded from the disk, then an modification made to the loaded file (either 45 A=23 or 45 GOTO 100). Then the file needs to be RUN.

When I try this by dragging and dropping I can select "GAME" to load, make the mod but the V64 screen then shifts right and the system freezes; nothing more can be done besides reboot.

I am unsure if this is something I am doing incorrectly, a feature I am overlooking or a bug.

Best regards,
Steve

**Comment by dirkwhoffmann** [comment]
Use `Insert...` from the `Drive` menu:

<img width="702" alt="Bildschirmfoto 2022-04-19 um 19 46 40" src="https://user-images.githubusercontent.com/12561945/164064740-108714ab-50f2-4d9f-97ef-a23f1a6dacf9.png">

**Comment by SJCunninghamHall** [comment]
Hi - thanks for the info. It's actually that menu option I was looking for and that is missing - no Drive 8 between the Keyboard and Datasette entries:

![image](https://user-images.githubusercontent.com/51404147/164441265-361bbe52-3e59-4348-a3e2-da7b0c781838.png)

**Comment by dirkwhoffmann** [comment]
OK, I see. This is either because there is no valid drive Rom installed or no drive drive is attached or both.

Check out these two panels: 

<img width="909" alt="Bildschirmfoto 2022-04-21 um 18 53 30" src="https://user-images.githubusercontent.com/12561945/164511853-91aee6a5-4182-4f99-a1a8-73605e57ac07.png">

<img width="909" alt="Bildschirmfoto 2022-04-21 um 18 53 54" src="https://user-images.githubusercontent.com/12561945/164511857-00e7a34a-4861-4712-8f05-7a9e9c8650f7.png">

**Comment by dirkwhoffmann** [comment]
> he ROM I was using for the drive wasn't working correctly

Sorry, I haven't seen your edit.
