### ISSUE TITLE
device Recognition in Virtual64

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#744]
VAmiga recognizes my mouse but virtual64 cant. See pic
<img width="1369" alt="Screenshot 2022-12-07 at 1 49 22 PM" src="https://user-images.githubusercontent.com/31462938/206272090-8b7dce98-b327-4ab9-9d77-0c5b78528e0a.png">

**Comment by dirkwhoffmann** [comment]
Up to now, only vAmiga supported external mice, because the mouse is a much more important input device on that machine. In the next release, VirtualC64 will support external mice, too. I didn't port the code earlier, because the method of distinguishing between the internal and the external mouse is kind of a hack and might fail in future macOS releases.

**Comment by dirkwhoffmann** [comment]
v4.6b1 is online.
